// Zentrale Übersetzungs-Datenbank für das gesamte IPSC-Portal
window.portalTranslations = {
    de: {
        // --- GEMEINSAME ELEMENTE & HEADER/FOOTER ---
        "main-title": "IPSC STARTPLATZ-BÖRSE",
        "sub-title": "Von Schützen für Schützen",
        "btn-login-reg": "Login / Registrieren",
        "logout": "Abmelden",
        "footer-impressum-link": "Impressum & Rechtliche Hinweise",
        "buy-coffee": "Kaffee spendieren",
        "btn-save": "Speichern",

        // --- NAVIGATION KEYS ---
        "nav-startseite": "Startseite",
        "nav-wiederladen": "Wiederladen",
        "nav-analytics": "Statistiken",
        "nav-sgtimer": "⏱️ SG-Timer Live",
        "card-title-schiessbuch": "Schießbuch",

        // --- STARTSEITE (index.html) ---
        "hero-title": "DVC – Willkommen auf deiner IPSC-Plattform",
        "hero-desc": "Die zentrale Anlaufstelle für IPSC-Schützen im deutschsprachigen Raum. Tausche Startplätze, finde freie Match-Plätze, diskutiere in der Community oder nutze unsere interaktiven Trainingstools.",
        "news-title": "📢 Neueste Plattform-Updates",
        "news-date-reload": "Juni 2026",
        "news-heading-reload": "📦 Neue Sektion: Wiederladen-Datenbank",
        "news-body-reload": "Die Wiederladen-Ecke ist ab sofort live! Speichere deine bewährten Laborierungen, Pulvermengen und OAL-Werte ab sofort sicher in deiner persönlichen Cloud ab und greife von der Range aus jederzeit darauf zu.",
        "news-date-1": "Juni 2026",
        "news-heading-1": "📱 Die IPSC-Börse als echte App (PWA)",
        "news-body-1": "Wir haben die Plattform 'App-ready' gemacht! Du kannst die Seite jetzt ganz einfach über deinen mobilen Browser (Safari/Chrome) über 'Zum Home-Bildschirm hinzufügen' als vollwertige App auf deinem Smartphone installieren – inklusive schickem IPSC-Scheiben-Icon.",
        "news-date-2": "Mai 2026",
        "news-heading-2": "⏱️ Neue Sektion: Tools & Training integriert",
        "news-body-2": "Ab sofort stehen dir mächtige Trainingshelfer zur Verfügung. Berechne präzise deinen Hit-Factor direkt auf der Range oder nutze unseren reaktionsschnellen Dry-Fire-Timer für dein Trockentraining zu Hause.",
        "news-date-3": "April 2026",
        "news-heading-3": "🛡️ 'Trusted Shooter' Reputationssystem",
        "news-body-3": "Um die Sicherheit auf dem Marktplatz zu maximieren, wurde ein Reputationssystem eingeführt. Durch Hinterlegen du deines IPSC-Alias erhältst du ein verifiziertes Abzeichen, zudem können erfolgreiche Vermittlungen gegenseitig bewertet werden.",
        "card-title-market": "Marktplatz",
        "card-desc-market": "Suche nach verfügbaren Startplätzen für ausgebuchte Matches oder biete dein eigenes Ticket zum Tausch an.",
        "card-action-market": "Zum Marktplatz &rarr;",
        "card-title-free": "Freie Match-Plätze",
        "card-desc-free": "Live-Auslastungs-Tracker für MatchSign. Finde sofort Turniere, die aktuell noch freie Plätze aufweisen.",
        "card-action-free": "Freie Plätze prüfen &rarr;",
        "card-title-planer": "Mein Planer",
        "card-desc-planer": "Plane deine perfekte IPSC-Saison, halte Fristen im Auge und exportiere deine Matches direkt in deinen Kalender.",
        "card-action-planer": "Saison planen &rarr;",
        "card-title-comm": "Community",
        "card-desc-comm": "Vernetze dich mit anderen Schützen, diskutiere über Ausrüstung und teile Beiträge im sozialen Feed.",
        "card-action-comm": "Zur Community &rarr;",
        "card-title-hub": "IPSC Hub",
        "card-desc-hub": "Schluss mit Suchen: Alle wichtigen Links zu MatchSign, PractiScore, IPSCess, Verbänden und Regelwerken gebündelt.",
        "card-action-hub": "Zum Link-Hub &rarr;",
        "card-title-tools": "Tools & Training",
        "card-desc-tools": "Interaktiver Hit-Factor-Rechner, Stage-Planungs-Assistent und ein konfigurierbarer Dry-Fire-Timer für dein Training.",
        "card-action-tools": "Zu den Tools &rarr;",

        // --- KONTO-EINSTELLUNGEN MODAL (ALLE SEITEN) ---
        "modal-settings-title": "Konto-Einstellungen",
        "modal-settings-deals": "📈 Erfolgreiche Vermittlungen",
        "modal-settings-seller": "Als Verkäufer",
        "modal-settings-buyer": "Als Käufer",
        "modal-settings-comm": "💬 Kommunikation:",
        "modal-settings-pay": "💳 Bezahlung:",
        "modal-settings-passkey-title": "🔒 Passkey (Schnell-Login)",
        "modal-settings-passkey-desc": "Hinterlege dein aktuelles Gerät, um dich künftig ohne Passwort per FaceID, Fingerabdruck oder PIN einzuloggen.",
        "modal-settings-passkey-btn": "Gerät als Passkey registrieren",
        "lbl-username": "Schützenname / Anzeigename",
        "lbl-ipsc-alias": "🛡️ IPSC Alias / Mitgliedsnummer",
        "lbl-ipsc-alias-desc": "Füllst du dieses Feld aus, erhältst du das 'Trusted Shooter' Badge an deinen Inseraten!",
        "lbl-real-name": "🔒 Echter Name (Für automatische Statistiken)",
        "lbl-real-name-desc": "Trage hier deinen Klarnamen ein (z. B. Max Mustermann). Dieser Name wird niemals öffentlich gezeigt. Er dient exklusiv dazu, dass der Nacht-Scraper deine Treffer auf ipscmatch.de findet.",
        "ph-real-name": "z.B. Max Mustermann",
        "lbl-profile-pic": "Profilbild (Optional)",
        "lbl-change-password": "Neues Passwort ändern (Optional)",
        "btn-delete-acc": "Konto & alle Einträge unwiderruflich löschen",
        
        // --- PLATZHALTER-ÜBERSETZUNGEN ---
        "ph-username": "z.B. IPSCShooter99",
        "ph-ipsc-alias": "z.B. GER1234 (Optional)",
        "ph-password": "Mindestens 6 Zeichen (Unverändert lassen für keine Änderung)",

        // --- MARKTPLATZ STATIC ELEMENTS (marktplatz.html) ---
        "info-msg": "<strong>Wichtiger Hinweis:</strong> Diese Plattform dient nur der Vermittlung. Die endgültige Umschreibung des Startplatzes muss zwingend über den jeweiligen Match Director durchgeführt werden!",
        "form-title": "Eintrag erstellen",
        "opt-offer": "Ich BIETE einen Startplatz an",
        "opt-want": "Ich SUCHE einen Startplatz",
        "lbl-name": "Name des Matches *",
        "lbl-level": "Match Level *",
        "lbl-date": "Datum des Matches *",
        "lbl-country": "Land *",
        "lbl-location": "Austragungsort (Stand) *",
        "lbl-squad": "Squad Nummer (Optional)",
        "lbl-price": "Abgabepreis (€) *",
        "lbl-email": "Deine E-Mail-Adresse *",
        "btn-cancel": "Abbrechen",
        "btn-insert": "Eintrag kostenlos veröffentlichen",
        "filter-type": "Anzeigentyp:",
        "filter-all": "Alle Anzeigen",
        "filter-offers": "Nur Angebote (Biete)",
        "filter-wants": "Nur Gesuche (Suche)",
        "list-title": "Aktuelle Marktplatz-Einträge",
        "loading": "Lade aktuelle Startplätze...",

        // --- MARKTPLATZ ERWEITERTE POPUPS ---
        "mediated-title": "Startplatz erfolgreich vermittelt",
        "mediated-desc": "Trage hier die E-Mail-Adresse des Käufers ein und bewerte die Transaktion, um sie abzuschließen. Die erfolgreiche Vermittlung wird in euren Profilstatistiken hinterlegt.",
        "lbl-buyer-email": "E-Mail-Adresse des Käufers *",
        "lbl-rating-comm": "💬 Kommunikation",
        "lbl-rating-pay": "💳 Bezahlung",
        "btn-mediated-submit": "Vermittlung bestätigen & Eintrag schließen",

        // --- MARKTPLATZ DYNAMIC TEXTS (app.js) ---
        "no-slots": "Aktuell keine Einträge verfügbar.",
        "btn-request": "Anbieter kontaktieren",
        "btn-contact-want": "Schützen kontaktieren",
        "btn-delete": "Löschen",
        "btn-edit": "Bearbeiten",
        "btn-export": "Export (.ics)",
        "report-btn": "Melden",
        "form-title-edit": "Eintrag bearbeiten ✏️",
        "btn-save-edit": "Änderungen speichern",
        "login-required": "Nur eingeloggte Nutzer können Schützen kontaktieren.",
        "tag-offer": "BIETE",
        "tag-want": "SUCHE",
        "spam-error": "Spam-Schutz: Du hast bereits einen Eintrag für dieses Match an diesem Datum erstellt!",
        "email-subject-offer": "Interesse an deinem IPSC Startplatz: ",
        "email-subject-want": "Bezüglich deiner Suche nach einem IPSC Startplatz: ",
        "email-body-offer": "Hallo,\n\ ich habe dein Inserat auf ipscboerse.com gesehen und interessiere mich für den von dir angebotenen Startplatz für das Match: ",
        "email-body-want": "Hallo,\n\ ich habe dein Gesuch auf ipscboerse.com gesehen. Ich hätte einen Startplatz abzugeben für das Match: ",
        "email-body-footer": "\n\nIst das Inserat noch aktuell?\n\nViele Grüße",
        "security-checklist": "\n\nSicherheits-Checkliste vor der E-Mail:\n- Match-Daten geprüft?\n- Match Director kontaktiert?",
        "security-notice": "⚠️ WICHTIGER SICHERHEITSHINWEIS:\n\n1. Nutze für Zahlungen IMMER PayPal mit Käuferschutz (niemals 'Freunde & Familie').\n2. Kontaktiere ZWINGEND den Match Director, BEVOR du Geld sendest, um zu prüfen, ob eine Umschreibung des Platzes überhaupt noch möglich ist!\n\nMöchtest du den E-Mail-Kontakt jetzt öffnen?",

        // --- FREIE MATCH-PLÄTZE (freie-matches.html) ---
        "free-info-box": "<strong>Info:</strong> Die Matches werden automatisch im Hintergrund aktualisiert. Es werden nur Turniere angezeigt, die eine Auslastung von unter 100% aufweisen (freie Startplätze).",
        "free-list-title": "Verfügbare Matches auf MatchSign (Auslastung < 100%)",
        "free-loading": "Lade aktuelle Matches...",

        // --- WETTKAMPFPLANER (mein-planer.html) ---
        "planner-logged-out-title": "Nicht angemeldet",
        "planner-logged-out-desc": "Logge dich ein, um deine Matches zu verwalten und in die Cloud zu synchronisieren.",
        "planner-logged-out-btn": "Jetzt einloggen",
        "planner-title-my-matches": "Meine Matches",
        "planner-subtitle-new": "Neues Match eintragen",
        "planner-lbl-match-name": "Match-Name",
        "planner-lbl-match-date": "Datum",
        "planner-lbl-match-location": "Ort / Land",
        "planner-btn-save": "Match in Cloud speichern",
        "planner-subtitle-planned": "Geplante Matches",
        "planner-loading": "Lade Daten aus Supabase...",
        "planner-btn-export": "📅 In Kalender exportieren (.ics)",
        "planner-no-matches": "Noch keine Matches eingetragen.",

        // --- COMMUNITY (community.html) ---
        "tab-posts": "Beiträge",
        "tab-groups": "Gruppen",
        "comm-logged-out-title": "Werde Teil der Community",
        "comm-logged-out-desc": "Bitte logge dich ein, um Beiträge zu lesen und mit anderen Schützen zu diskutieren.",
        "comm-logged-out-btn": "Jetzt einloggen",
        "comm-setup-title": "Wähle deinen Schützennamen",
        "comm-setup-desc": "Bevor du in der Community starten kannst, wähle bitte einen Schützennamen / Anzeigenamen (z.B. IPSCShooter99).",
        "comm-setup-btn": "Namen speichern & starten",
        "comm-loading": "Lade Beiträge...",
        "fab-create-post": "+ Beitrag erstellen",
        "comm-groups-coming": "Gruppen-Funktion (Coming Soon)",
        "comm-groups-desc": "Hier wirst du bald private Squad-Gruppen oder Vereins-Kanäle erstellen können.",
        "modal-new-post": "Neuer Beitrag",
        "lbl-add-photo": "Foto hinzufügen (Optional)",
        "btn-share-post": "Teilen",

        // --- LOGIN & AUTH MODALS ---
        "modal-login-title": "Anmelden",
        "link-forgot-pwd": "Passwort vergessen?",
        "modal-btn-login": "Mit Passwort einloggen",
        "modal-no-acc": "Noch kein Konto?",
        "modal-link-reg": "Registrieren",
        "modal-reg-title": "Konto erstellen",
        "modal-has-acc": "Bereits registriert?",
        "modal-link-login": "Zum Login",
        "modal-forgot-title": "Passwort vergessen",
        "modal-btn-forgot": "Zurücksetzungs-Link senden",
        "modal-reset-title": "Neues Passwort vergeben",
        "lbl-new-password": "Neues Passwort *",

        // --- TOOLS (tools.html) ---
        "tools-hf-title": "🏆 Hit-Factor Battle",
        "tools-hf-desc": "Trage die Ergebnisse von dir und deinen Freunden ein, um eine Live-Rangliste für die Stage zu erstellen.",
        "tools-hf-name": "Schützenname",
        "tools-hf-pf": "Wertung",
        "tools-hf-time": "Zeit (Sek.)",
        "tools-hf-scoring": "Trefferaufnahme",
        "tools-hf-alpha": "Alpha (A)",
        "tools-hf-charlie": "Charlie (C)",
        "tools-hf-delta": "Delta (D)",
        "tools-hf-miss": "Miss (M)",
        "tools-hf-ns": "No-Shoot",
        "tools-hf-btn-submit": "Schütze eintragen & berechnen",
        "tools-th-name": "Name",
        "tools-th-pts": "Pts",
        "tools-th-time": "Zeit",
        "tools-th-hf": "HF",
        "tools-hf-btn-clear": "Rangliste leeren",
        "tools-df-title": "⏱️ Dry-Fire Timer & Drill Generator",
        "tools-df-placeholder": "Klicke auf den Button, um einen zufälligen Trockentrainings-Ablauf zu generieren.",
        "tools-df-btn-gen": "🎲 Neuen Drill generieren",
        "tools-df-par": "Par-Zeit (Sekunden)",
        "tools-df-status-ready": "Bereit",
        "tools-df-btn-start": "Start Timer (Zufalls-Delay)",
        "tools-pf-title": "⏱️ IPSC Power-Factor Manager",
        "tools-pf-desc": "Berechne den Power Factor deiner Laborierung und überprüfe den Status für das Match.",
        "tools-pf-weight": "Geschossgewicht (Grains)",
        "tools-pf-velocity": "Geschwindigkeit (fps)",
        "tools-pf-target": "Angestrebte Wertung",
        "tools-pf-opt-minor": "Minor (Mindest-Faktor 125)",
        "tools-pf-opt-major": "Major (Mindest-Faktor 160)",
        "tools-pf-result-label": "Errechneter Power Factor",
        "tools-db-title": "📦 Meine Wiederlade-Rezepte",
        "tools-db-desc": "Speichere deine bewährten Laborierungen dauerhaft in deiner Cloud ab.",
        "tools-db-logged-out": "Logge dich ein, um deine persönliche Wiederlade-Datenbank zu nutzen und Rezepte in der Cloud zu speichern.",
        "tools-db-caliber": "Kaliber",
        "tools-db-bullet-type": "Geschosstyp / Hersteller",
        "tools-db-bullet-type-ph": "z.B. LOS HP oder H&N HS",
        "tools-db-powder": "Pulver (Sorte & Menge)",
        "tools-db-powder-ph": "z.B. 3.7gr N320",
        "tools-db-oal": "OAL (mm)",
        "tools-db-oal-ph": "z.B. 29.00",
        "tools-db-notes": "Notizen / Waffe (Optional)",
        "tools-db-notes-ph": "z.B. Sicherer Minor-Faktor aus CZ Shadow 2",
        "tools-db-btn-save": "💾 Rezept in Cloud speichern",
        "tools-db-saved-title": "Gespeicherte Cloud-Laborierungen",

        // --- IPSC HUB ---
        "hub-main-title": "IPSC Hub – Alle wichtigen Links",
        "hub-main-desc": "Schluss mit dem ewigen Suchen: Hier findest du zentral gebündelt alle wichtigen Plattformen für Match-Anmeldungen, Ergebnisse und Verbandsinfos rund um unser Hobby.",
        "hub-cat-management": "🎯 Match-Anmeldungen & Verwaltung",
        "hub-desc-matchsign": "Die bekannteste und meistgenutzte Plattform für IPSC Match-Anmeldungen in Deutschland.",
        "hub-btn-matchsign": "Zu MatchSign",
        "hub-desc-ipscess": "Offizielles Portal für die Verwaltung von Lizenzen, Matchpunkten und dem IPSC-Ausweis.",
        "hub-btn-ipscess": "Zum IPSCess Portal",
        "hub-desc-practiscore": "Das internationale System. Unverzichtbar für ausländische Matches und Live-Scoring vor Ort.",
        "hub-btn-practiscore": "Zu PractiScore",
        "hub-desc-makeready": "Häufig genutzt für große internationale Turniere und Matches im europäischen Umland.",
        "hub-btn-makeready": "Zu MakeReady",
        "hub-cat-stats": "📊 Statistiken & Rankings",
        "hub-desc-ipscelo": "Inoffizielles, aber fantastisches Elo-Ranking und Statistik-Tool basierend auf internationalen Match-Ergebnissen.",
        "hub-btn-ipscelo": "Zu IPSCelo",
        "hub-cat-rules": "📖 Verbände & Regelwerke",
        "hub-desc-bds": "Der Bund Deutscher Sportschützen. Offizielle Anlaufstelle für Sportordnung, Befürwortungen und Termine.",
        "hub-btn-bds": "Zum BDS",
        "hub-desc-rules": "Die aktuellen internationalen Regelwerke (Handgun, Rifle, PCC, Shotgun) direkt als PDF zum Download.",
        "hub-btn-rules": "Zu den Rulebooks",

        // --- PERFORMANCE ANALYTICS & DASHBOARD ---
        "analytics-title": "🏆 IPSC Performance Analytics",
        "analytics-desc": "Überwache deine sportliche Entwicklung, deine Treffer-Präzision und deine Hit-Factor-Trends der letzten Matches.",
        "analytics-kpi-matches": "Matches Gesamt",
        "analytics-kpi-avg-hf": "Ø Hit Factor",
        "analytics-chart-title": "📈 Hit-Factor Trend (Letzte 5 Stages)",
        "analytics-acc-title": "🎯 Treffer-Verteilung (Präzision)",
        "analytics-box-title": "📧 A, C, D automatisch eintragen",
        "analytics-box-desc": "Ergebnisse und Hitfaktor werden automatisch geladen. Wer auch <strong>A, C, D und Misses</strong> automatisch drin haben will, leitet seine PractiScore-Mails nach dem Match einfach an <strong style='color: var(--text-color);'>info@ipscboerse.com</strong> weiter!",

        // --- IMPRESSUM & RECHTLICHES (DE) ---
        "imp-back": "← Zurück zur Startseite",
        "imp-h2-1": "1. Impressum",
        "imp-p-1": "<strong>Angaben gemäß § 5 TMG:</strong><br>Fabian Schöps<br>Weserblick 9<br>34399 Wesertal",
        "imp-p-contact": "<strong>Kontakt:</strong><br>E-Mail: <a href='mailto:info@ipscboerse.com'>info@ipscboerse.com</a>",
        "imp-h2-2": "2. Allgemeine Geschäftsbedingungen (AGB) & Nutzungsbedingungen",
        "imp-h3-1": "§ 1 Geltungsbereich und Zweck der Plattform",
        "imp-p-2": "Die Plattform (ipscboerse.com) stellt ausschließlich eine technische Infrastruktur zur Verfügung (\"Schwarzes Brett\"), um Sportschützen untereinander zur Vermittlung von Startplätzen zu vernetzen. Der Betreiber dieser Webseite tritt <strong>nicht</strong> als Veranstalter, Käufer, Verkäufer oder offizieller Vermittler von Startplätzen auf. Verträge über den Startplatztausch kommen ausschließlich zwischen den beteiligten Nutzern zustande.",
        "imp-h3-2": "§ 2 Pflichten der Nutzer & Verhaltensregeln",
        "imp-p-3": "Nutzer verpflichten sich, die Plattform ausschließlich für den vorgesehenen legalen Zweck zu nutzen. Es ist strengstens untersagt, Inhalte (Beiträge, Chat-Nachrichten, Kommentare oder Bilder) zu veröffentlichen, die:",
        "imp-li-1": "Beleidigungen, Verleumdungen, Bedrohungen, Hate Speech, Rassismus oder Diskriminierungen enthalten.",
        "imp-li-2": "Pornografische, sexuell anstößige (einschließlich kommerzieller Bademode/Unterwäsche) oder jugendgefährdende Motive zeigen.",
        "imp-li-3": "Gewaltverherrlichendes, extremistisches oder verfassungsfeindliches Material darstellen.",
        "imp-li-4": "Gegen geltendes Recht (z.B. Urheberrecht, Strafrecht) verstoßen oder Spam bzw. betrügerische Absichten verfolgen.",
        "imp-li-5": "Dem gewerblichen oder gewinnorientierten Ticket-Weiterverkauf (Reselling/Scalping) dienen. Startplätze dürfen maximal zum offiziellen Originalpreis des Veranstalters angeboten werden.",
        "imp-h3-3": "§ 3 Automatisierte Moderation & Hausrecht",
        "imp-p-4": "Um die Sicherheit, Jugendfreiheit und Qualität des Marktplatzes zu gewährleisten, setzt der Betreiber automatisierte Filter- und KI-Systeme zur Echtzeit-Moderation ein:",
        "imp-li-6": "<strong>Text Filter:</strong> Alle eingestellten Beiträge und Kommentare werden vollautomatisch auf eine integrierte Liste unzulässiger Begriffe und Schimpwörter geprüft.",
        "imp-li-7": "<strong>Bild KI:</strong> Hochgeladene Bilddateien werden softwareseitig mittels künstlicher Intelligenz auf visuelle Richtlinienverstöße (wie z.B. Nacktheit oder Teilnacktheit) gescannt.",
        "imp-p-5": "Verstört ein Beitrag oder Kommentar gegen diese Richtlinien, wird der Eintrag durch das System <span class='highlight'>sofort, vollautomatisch und ohne Vorwarnung unwiderruflich gelöscht</span>. Der Betreiber behält sich im Rahmen seines Hausrechts das Recht vor, Nutzerkonten bei Verstößen temporär oder dauerhaft zu sperren.",
        "imp-h3-4": "§ 4 Haftungsausschluss (Disclaimer)",
        "imp-p-6": "Wir übernehmen ausdrücklich keine Haftung für:",
        "imp-li-8": "Das tatsächliche Zustandekommen von Startplatz-Übertragungen.",
        "imp-li-9": "Die Richtigkeit der von Nutzern im Chat oder in Inseraten eingestellten Match-Daten, Fristen oder Preise.",
        "imp-li-10": "Finanzielle Verluste oder Schäden durch Betrug oder Unstimmigkeiten zwischen Nutzern.",
        "imp-li-11": "Die finale Entscheidung des jeweiligen Match Directors (Veranstalters), ob eine Umschreibung akzeptiert wird.",
        "imp-alert-title": "WICHTIGER HINWEIS ZUR ABWICKLUNG:",
        "imp-alert-desc": "Die finanzielle Abwicklung und die finale Umschreibung beim Match Director obliegen zu 100 % der Verantwortung der jeweiligen Nutzer. Wir raten dringend dazu, Zahlungen ausschließlich über sichere Methoden (z. B. PayPal mit Käuferschutz) abzuwickeln und VOR einer Zahlung die ausdrückliche Zustimmung des Veranstalters einzuholen.",
        "imp-h2-3": "3. Datenschutzerklärung",
        "imp-p-7": "Wir nehmen den Schutz deiner persönlichen Daten sehr ernst. Diese Datenschutzerklärung klärt dich über die Art, den Umfang und Zweck der Verarbeitung von personenbezogenen Daten auf unserer Plattform auf.",
        "imp-h3-5": "1. Verantwortlicher für die Datenverarbeitung",
        "imp-p-8": "Verantwortlich für die Datenverarbeitung ist der oben im Impressum genannte Betreiber dieser Webseite.",
        "imp-h3-6": "2. Erfassung und Verarbeitung von Nutzerdaten",
        "imp-p-9": "Um Inserate zu erstellen, den Live-Chat zu nutzen oder Anbieter zu kontaktieren, musst du ein Benutzerkonto anlegen. Dabei erfassen wir folgende Daten:",
        "imp-li-12": "<strong>E-Mail-Adresse:</strong> Notwendig für den Login, die Verifizierung, Systembenachrichtigungen, die Zuordnung von Chat-Nachrichten und die Kontaktaufnahme.",
        "imp-li-13": "<strong>Passwort:</strong> Wird kryptografisch verschlüsselt gespeichert (kein Klartextzugriff für den Betreiber).",
        "imp-li-14": "<strong>Benutzername (Optional):</strong> Zur Darstellung auf der Plattform innerhalb deiner Beiträge.",
        "imp-li-15": "<strong>Chat-Nachrichten:</strong> Im Rahmen des integrierten Live-Chats ausgetauschte Nachrichtenverläufe werden zur Bereitstellung der Chat-Funktion in der Datenbank gespeichert.",
        "imp-li-16": "<strong>Nutzergenerierte Inhalte:</strong> Eingestellte Match-Daten, Beschreibungen, Preise, Kommentare sowie hochgeladene Bilder.",
        "imp-h3-7": "3. Sichtbarkeit deiner Daten & Funktionsweise des Live-Chats",
        "imp-p-10": "Das Kernprinzip dieser Börse ist die Vermittlung von Startplätzen. <strong>Wenn du ein Inserat erstellst oder den Live-Chat nutzt, sind die beteiligten Daten für die jeweiligen Chat-Partner einsehbar.</strong> Innerhalb der Marktplatz-Inserate ist deine E-Mail-Adresse für andere eingeloggte Nutzer abrufbar, um die Kontaktaufnahme zu ermöglichen (Art. 6 Abs. 1 lit. a und lit. b DSGVO).",
        "imp-p-11": "Zusätzlich steht im Live-Chat eine manuelle Funktion zur Verfügung, mit der Nutzer ihren Chat-Partner per E-Mail anstupsen können. Hierbei öffnet sich das lokale E-Mail-Programm des Nutzers via Mailto-Link autark; es findet über diese Schnittstelle keine automatisierte Datenweiterleitung im Hintergrund an Drittanbieter statt.",
        "imp-h3-8": "4. Automated Content Verification & Data Transmission",
        "imp-p-12": "Zur Wahrung unseres berechtigten Interesses an einer sicheren, gesetzeskonformen und störungsfreien Plattform (Art. 6 Abs. 1 lit. f DSGVO) werden Inhalte wie folgt verarbeitet:",
        "imp-li-17": "<strong>Bild-Scans (Sightengine):</strong> Beim Hochladen eines Bildes wird dessen URL automatisiert an die Programmierschnittstelle des Prüfdienstes Sightengine (Sightengine SAS, Frankreich/EU) übermittelt. Das Bild wird dort rein maschinell auf Verstöße (z.B. Filter für Nacktheit) analysiert. Es findet keine dauerhafte Speicherung oder Nutzung der Bilder für Drittzwecke oder KI-Training durch den Dienstleister statt.",
        "imp-h3-9": "5. Nutzung von Supabase (Hosting, Datenspeicherung & Live-Chat)",
        "imp-p-13": "Diese Webseite nutzt für die zentrale Datenbank, das Speichern von Chat-Verläufen (Live-Chat), die Datei-Speicherung (Storage) und die Nutzer-Authentifizierung den Backend-Dienst „Supabase“ (Supabase Inc., San Francisco, USA). Deine Daten werden auf den von Supabase bereitgestellten Infrastrukturen innerhalb der EU (Region: Frankfurt am Main, Deutschland) gehostet und verarbeitet. Wir haben mit dem Anbieter einen rechtskräftigen Vertrag zur Auftragsverarbeitung (Data Processing Addendum, DPA) gemäß Art. 28 DSGVO abgeschlossen. Weitere Infos: <a href='https://supabase.com/privacy' target='_blank' rel='noopener'>Supabase Privacy</a>.",
        "imp-h3-10": "6. Match-Analytics & Ergebnis-Scraper",
        "imp-p-14": "Wenn du auf unserer Plattform deinen echten Namen in den Profileinstellungen hinterlegst, nutzen wir auf deine ausdrückliche Anforderung hin automatisierte Systeme, um öffentlich zugängliche Ergebnislisten von IPSC-Turnieren im Internet nach diesem Namen zu durchsuchen. Die gefundenen, dich betreffenden Trefferdaten (wie Matchname, Stage, Faktoren) werden in unsere Datenbank importiert, um dir deine Statistiken anzuzeigen (Art. 6 Abs. 1 lit. b DSGVO). <strong>Wichtig:</strong> Daten dritter Personen, die sich ebenfalls auf diesen Listen befinden, werden von unseren Systemen lediglich flüchtig im Arbeitsspeicher verarbeitet und sofort verworfen. Es findet keinerlei Speicherung oder Profilbildung fremder Personendaten statt.",
        "imp-h3-11": "7. Cookies & Local Storage",
        "imp-p-15": "Um deinen Login-Status über Browsersitzungen hinweg aufrechtzuerhalten, speichert Supabase ein Authentifizierungs-Token im 'Local Storage' deines Endgeräts. Dies ist ein technisch zwingend notwendiger Vorgang (Art. 6 Abs. 1 lit. f DSGVO). Es werden keine Marketing-, Tracking- oder Werbe-Cookies eingesetzt.",
        "imp-h3-12": "8. Ergebnisbezogene Löschung von Daten",
        "imp-p-16": "Du kannst in deinen Konto-Einstellungen mit einem Klick auf 'Konto & alle Einträge unwiderruflich löschen' dein gesamtes Profil, all deine Inserate, verfassten Kommentare sowie deine gesamten persönlichen Chat-Verläufe sofort, dauerhaft und unwiderruflich aus unserer Live-Datenbank entfernen.",
        "imp-h3-13": "9. Deine Rechte",
        "imp-p-17": "Nach der DSGVO hast du das Recht auf unentgeltliche Auskunft über deine gespeicherten Daten, Berichtigung, Sperrung oder Löschung dieser Daten sowie das Recht auf Datenübertragbarkeit. Wende dich hierfür jederzeit an die im Impressum angegebene E-Mail-Adresse."
    },
    en: {
        // --- COMMON ELEMENTS & HEADER/FOOTER ---
        "main-title": "IPSC SLOT MARKETPLACE",
        "sub-title": "By Shooters for Shooters",
        "btn-login-reg": "Login / Register",
        "logout": "Logout",
        "footer-impressum-link": "Legal Notice & Disclaimers",
        "buy-coffee": "Buy me a coffee",
        "btn-save": "Save Changes",

        // --- NAVIGATION KEYS ---
        "nav-startseite": "Home",
        "nav-wiederladen": "Reloading",
        "nav-analytics": "Analytics",
        "nav-sgtimer": "⏱️ SG-Timer Live",
        "card-title-schiessbuch": "Shooting Log",

        // --- HOME PAGE (index.html) ---
        "hero-title": "DVC – Welcome to your IPSC Platform",
        "hero-desc": "The central hub for IPSC shooters in the German-speaking region. Exchange starting slots, find available match slots, discuss in the community or use our interactive training tools.",
        "news-title": "📢 Latest Platform Updates",
        "news-date-reload": "June 2026",
        "news-heading-reload": "📦 New Section: Reloading Database",
        "news-body-reload": "The reloading corner is officially live! Save your proven loads, powder charges, and OAL values safely to your personal cloud database and access them anytime straight from the range.",
        "news-date-1": "June 2026",
        "news-heading-1": "📱 The IPSC Exchange as a real App (PWA)",
        "news-body-1": "We made the platform 'App-ready'! You can now easily install the site via your mobile browser (Safari/Chrome) using 'Add to Home Screen' as a full app on your smartphone – including a stylish IPSC target icon.",
        "news-date-2": "May 2026",
        "news-heading-2": "⏱️ New Section: Tools & Training integrated",
        "news-body-2": "From now on, powerful training helpers are available to you. Calculate your hit factor precisely directly on the range or use our responsive dry-fire timer for your dry training at home.",
        "news-date-3": "April 2026",
        "news-heading-3": "🛡️ 'Trusted Shooter' Reputation System",
        "news-body-3": "To maximize security on the marketplace, a reputation system was introduced. By storing your IPSC alias you receive a verified badge, and successful deals can be rated mutually.",
        "card-title-market": "Marketplace",
        "card-desc-market": "Search for available starting slots for fully booked matches or offer your own ticket for exchange.",
        "card-action-market": "To Marketplace &rarr;",
        "card-title-free": "Available Match Slots",
        "card-desc-free": "Live capacity tracker for MatchSign. Find tournaments instantly that currently still have free slots.",
        "card-action-free": "Check free slots &rarr;",
        "card-title-planer": "My Planner",
        "card-desc-planer": "Plan your perfect IPSC season, keep an eye on deadlines and export your matches directly to your calendar.",
        "card-action-planer": "Plan season &rarr;",
        "card-title-comm": "Community",
        "card-desc-comm": "Network with other shooters, discuss equipment and share posts in the social feed.",
        "card-action-comm": "To Community &rarr;",
        "card-title-hub": "IPSC Hub",
        "card-desc-hub": "No more searching: All important links to MatchSign, PractiScore, IPSCess, associations and rulebooks bundled.",
        "card-action-hub": "To Link Hub &rarr;",
        "card-title-tools": "Tools & Training",
        "card-desc-tools": "Interactive hit factor calculator, stage planning assistant and a configurable dry-fire timer for your training.",
        "card-action-tools": "To Tools &rarr;",

        // --- KONTO-EINSTELLUNGEN MODAL (ALLE SEITEN) ---
        "modal-settings-title": "Account Settings",
        "modal-settings-deals": "📈 Successful Mediations",
        "modal-settings-seller": "As Seller",
        "modal-settings-buyer": "As Buyer",
        "modal-settings-comm": "💬 Communication:",
        "modal-settings-pay": "💳 Payment:",
        "modal-settings-passkey-title": "🔒 Passkey (Quick Login)",
        "modal-settings-passkey-desc": "Link your current device to log in without a password via FaceID, fingerprint, or PIN in the future.",
        "modal-settings-passkey-btn": "Register device as Passkey",
        "lbl-username": "Shooter Name / Display Name",
        "lbl-ipsc-alias": "🛡️ IPSC Alias / Member Number",
        "lbl-ipsc-alias-desc": "If you fill in this field, you will receive the 'Trusted Shooter' badge on your listings!",
        "lbl-real-name": "🔒 Real Name (For automatic analytics)",
        "lbl-real-name-desc": "Enter your real name here (e.g., John Doe). This name will never be displayed publicly. It is only used by the night scraper to map your match hits.",
        "ph-real-name": "e.g. John Doe",
        "lbl-profile-pic": "Profile Picture (Optional)",
        "lbl-change-password": "Change New Password (Optional)",
        "btn-delete-acc": "Irrevocably delete account & all entries",
        
        // --- PLATZHALTER-ÜBERSETZUNGEN ---
        "ph-username": "e.g. IPSCShooter99",
        "ph-ipsc-alias": "e.g. GER1234 (Optional)",
        "ph-password": "At least 6 characters (Leave blank to keep current)",

        // --- MARKETPLACE STATIC ELEMENTS (marktplatz.html) ---
        "info-msg": "<strong>Important Notice:</strong> This platform is for mediation purposes only. The final reassignment of the starting slot must be processed by the respective Match Director!",
        "form-title": "Create Entry",
        "opt-offer": "I AM OFFERING a starting slot",
        "opt-want": "I AM LOOKING FOR a starting slot",
        "lbl-name": "Match Name *",
        "lbl-level": "Match Level *",
        "lbl-date": "Match Date *",
        "lbl-country": "Country *",
        "lbl-location": "Range Location *",
        "lbl-squad": "Squad Number (Optional)",
        "lbl-price": "Asking Price (€) *",
        "lbl-email": "Your Email Address *",
        "btn-cancel": "Cancel",
        "btn-insert": "Publish Entry for Free",
        "filter-type": "Listing Type:",
        "filter-all": "All Listings",
        "filter-offers": "Offers Only (Selling)",
        "filter-wants": "Requests Only (Buying)",
        "list-title": "Current Marketplace Entries",
        "loading": "Loading available slots...",

        // --- MARKETPLACE ERWEITERTE POPUPS ---
        "mediated-title": "Slot Successfully Mediated",
        "mediated-desc": "Enter the buyer's email address here and rate the transaction to complete it. The successful mediation will be stored in your profile statistics.",
        "lbl-buyer-email": "Buyer's Email Address *",
        "lbl-rating-comm": "💬 Communication",
        "lbl-rating-pay": "💳 Payment",
        "btn-mediated-submit": "Confirm Mediation & Close Entry",

        // --- MARKETPLACE DYNAMIC JAVASCRIPT TEXTS (app.js) ---
        "no-slots": "No marketplace entries available.",
        "btn-request": "Contact Seller",
        "btn-contact-want": "Contact Shooter",
        "btn-delete": "Delete",
        "btn-edit": "Edit",
        "btn-export": "Export (.ics)",
        "report-btn": "Report",
        "form-title-edit": "Edit Entry ✏️",
        "btn-save-edit": "Save Changes",
        "login-required": "Only logged-in users can contact shooters.",
        "tag-offer": "OFFER",
        "tag-want": "WANTED",
        "spam-error": "Spam protection: You have already posted an entry for this match on this date!",
        "email-subject-offer": "Inquiry regarding your IPSC slot: ",
        "email-subject-want": "Regarding your request for an IPSC slot: ",
        "email-body-offer": "Hello,\n\nI saw your listing on ipscboerse.com and I am interested in the slot you offered for the match: ",
        "email-body-want": "Hello,\n\nI saw your request on ipscboerse.com. I have an available slot to give away for the match: ",
        "email-body-footer": "\n\nIs this listing still available?\n\nBest regards",
        "security-checklist": "\n\nSecurity checklist before email:\n- Match details verified?\n- Match Director contacted?",
        "security-notice": "⚠️ IMPORTANT SAFETY NOTICE:\n\n1. ALWAYS use PayPal with Buyer Protection for payments (never use 'Friends & Family').\n2. You MUST contact the Match Director BEFORE making any payment to confirm if a slot transfer is still permitted!\n\nDo you want to open the email client now?",

        // --- AVAILABLE MATCH SLOTS (freie-matches.html) ---
        "free-info-box": "<strong>Info:</strong> Matches are updated automatically in the background. Only tournaments with a capacity under 100% are displayed (free slots available).",
        "free-list-title": "Available Matches on MatchSign (Capacity < 100%)",
        "free-loading": "Loading current matches...",

        // --- COMPETITION PLANNER (mein-planer.html) ---
        "planner-logged-out-title": "Not Logged In",
        "planner-logged-out-desc": "Log in to make modifications to your matches and synchronize files with the cloud.",
        "planner-logged-out-btn": "Log In Now",
        "planner-title-my-matches": "My Matches",
        "planner-subtitle-new": "Add New Match",
        "planner-lbl-match-name": "Match Name",
        "planner-lbl-match-date": "Date",
        "planner-lbl-match-location": "Location / Country",
        "planner-btn-save": "Save Match to Cloud",
        "planner-subtitle-planned": "Planned Matches",
        "planner-loading": "Loading data from Supabase...",
        "planner-btn-export": "📅 Export to Calendar (.ics)",
        "planner-no-matches": "No matches added yet.",

        // --- COMMUNITY (community.html) ---
        "tab-posts": "Posts",
        "tab-groups": "Groups",
        "comm-logged-out-title": "Join the Community",
        "comm-logged-out-desc": "Please log in to read posts and discuss with other shooters.",
        "comm-logged-out-btn": "Log In Now",
        "comm-setup-title": "Choose your Alias",
        "comm-setup-desc": "Before starting in the community, please choose a shooter alias / display name (e.g., IPSCShooter99).",
        "comm-setup-btn": "Save Name & Start",
        "comm-loading": "Loading posts...",
        "fab-create-post": "Create Post",
        "comm-groups-coming": "Groups Feature (Coming Soon)",
        "comm-groups-desc": "Here you will soon be able to create private squad groups or club channels.",
        "modal-new-post": "New Post",
        "lbl-add-photo": "Add Photo (Optional)",
        "btn-share-post": "Share",

        // --- LOGIN & AUTH MODALS ---
        "modal-login-title": "Login",
        "link-forgot-pwd": "Forgot password?",
        "modal-btn-login": "Log in with Password",
        "modal-no-acc": "Don't have an account?",
        "modal-link-reg": "Register",
        "modal-reg-title": "Create Account",
        "modal-has-acc": "Already registered?",
        "modal-link-login": "To Login",
        "modal-forgot-title": "Forgot Password",
        "modal-btn-forgot": "Send Reset Link",
        "modal-reset-title": "Assign New Password",
        "lbl-new-password": "New Password *",

        // --- TOOLS (tools.html) ---
        "tools-hf-title": "🏆 Hit-Factor Battle",
        "tools-hf-desc": "Enter the results of you and your friends to create a live leaderboard for the stage.",
        "tools-hf-name": "Shooter Name",
        "tools-hf-pf": "Power Factor",
        "tools-hf-time": "Time (Sec.)",
        "tools-hf-scoring": "Scoring / Hits",
        "tools-hf-alpha": "Alpha (A)",
        "tools-hf-charlie": "Charlie (C)",
        "tools-hf-delta": "Delta (D)",
        "tools-hf-miss": "Miss (M)",
        "tools-hf-ns": "No-Shoot",
        "tools-hf-btn-submit": "Enter Shooter & Calculate",
        "tools-th-name": "Name",
        "tools-th-pts": "Pts",
        "tools-th-time": "Time",
        "tools-th-hf": "HF",
        "tools-hf-btn-clear": "Clear Leaderboard",
        "tools-df-title": "⏱️ Dry-Fire Timer & Drill Generator",
        "tools-df-placeholder": "Click the button to generate a random dry fire training drill.",
        "tools-df-btn-gen": "🎲 Generate New Drill",
        "tools-df-par": "Par Time (Seconds)",
        "tools-df-status-ready": "Ready",
        "tools-df-btn-start": "Start Timer (Random Delay)",
        "tools-pf-title": "⏱️ IPSC Power-Factor Manager",
        "tools-pf-desc": "Calculate the power factor of your load and check the match status.",
        "tools-pf-weight": "Bullet Weight (Grains)",
        "tools-pf-velocity": "Velocity (fps)",
        "tools-pf-target": "Target Scoring",
        "tools-pf-opt-minor": "Minor (Minimum Factor 125)",
        "tools-pf-opt-major": "Major (Minimum Factor 160)",
        "tools-pf-result-label": "Calculated Power Factor",
        "tools-db-title": "📦 My Reloading Recipes",
        "tools-db-desc": "Save your proven loads permanently to your secure cloud database.",
        "tools-db-logged-out": "Log in to access your personal reloading recipe database and synchronize files with the cloud.",
        "tools-db-caliber": "Caliber",
        "tools-db-bullet-type": "Bullet Type / Maker",
        "tools-db-bullet-type-ph": "e.g. LOS HP or H&N HS",
        "tools-db-powder": "Powder (Type & Amount)",
        "tools-db-powder-ph": "e.g. 3.7gr N320",
        "tools-db-oal": "OAL (mm)",
        "tools-db-oal-ph": "e.g. 29.00",
        "tools-db-notes": "Notes / Gun (Optional)",
        "tools-db-notes-ph": "e.g. Safe minor factor out of CZ Shadow 2",
        "tools-db-btn-save": "💾 Save Recipe to Cloud",
        "tools-db-saved-title": "Saved Cloud Loads",

        // --- IPSC HUB ---
        "hub-main-title": "IPSC Hub – All Important Links",
        "hub-main-desc": "No more endless searching: All important links to MatchSign, PractiScore, IPSCess, associations and rulebooks bundled.",
        "hub-cat-management": "🎯 Match Registrations & Management",
        "hub-desc-matchsign": "The most well-known and used platform for IPSC match registrations in Germany.",
        "hub-btn-matchsign": "Go to MatchSign",
        "hub-desc-ipscess": "Official portal for managing licenses, match points, and the IPSC ID card.",
        "hub-btn-ipscess": "Go to IPSCess Portal",
        "hub-desc-practiscore": "The international system. Essential for foreign matches and live scoring on-site.",
        "hub-btn-practiscore": "Go to PractiScore",
        "hub-desc-makeready": "Frequently used for large international tournaments and matches in neighboring European countries.",
        "hub-btn-makeready": "Go to MakeReady",
        "hub-cat-stats": "📊 Statistics & Rankings",
        "hub-desc-ipscelo": "Unofficial but fantastic Elo ranking and statistics tool based on international match results.",
        "hub-btn-ipscelo": "Go to IPSCelo",
        "hub-cat-rules": "📖 Associations & Rulebooks",
        "hub-desc-bds": "The Federation of German Sport Shooters. Official contact point for sports regulations, endorsements, and dates.",
        "hub-btn-bds": "Go to BDS",
        "hub-desc-rules": "The current international rulebooks (Handgun, Rifle, PCC, Shotgun) directly as PDF for download.",
        "hub-btn-rules": "Go to Rulebooks",

        // --- PERFORMANCE ANALYTICS & DASHBOARD ---
        "analytics-title": "🏆 IPSC Performance Analytics",
        "analytics-desc": "Track your athletic progress, shooting precision, and hit factor trends across your matches.",
        "analytics-kpi-matches": "Total Matches",
        "analytics-kpi-avg-hf": "Avg Hit Factor",
        "analytics-chart-title": "📈 Hit Factor Trend (Last 5 Stages)",
        "analytics-acc-title": "🎯 Hit Distribution (Accuracy)",
        "analytics-box-title": "📧 Enter A, C, D automatically",
        "analytics-box-desc": "Results and hit factor are loaded automatically. If you also want <strong>A, C, D and Misses</strong> entered automatically, simply forward your PractiScore emails to <strong style='color: var(--text-color);'>info@ipscboerse.com</strong> after the match!",

        // --- IMPRESSUM & RECHTLICHES (EN) ---
        "imp-back": "← Back to home",
        "imp-h2-1": "1. Legal Notice (Impressum)",
        "imp-p-1": "<strong>Information pursuant to § 5 TMG:</strong><br>Fabian Schöps<br>Weserblick 9<br>34399 Wesertal, Germany",
        "imp-p-contact": "<strong>Contact:</strong><br>Email: <a href='mailto:info@ipscboerse.com'>info@ipscboerse.com</a>",
        "imp-h2-2": "2. Terms and Conditions (T&C) & Terms of Use",
        "imp-h3-1": "§ 1 Scope and Purpose of the Platform",
        "imp-p-2": "The platform (ipscboerse.com) provides exclusively a technical infrastructure ('bulletin board') to connect sports shooters with each other for the transfer of match slots. The operator of this website does <strong>not</strong> act as an organizer, buyer, seller, or official intermediary of starting slots. Contracts for slot exchanges are made exclusively between the participating users.",
        "imp-h3-2": "§ 3 User Obligations & Code of Conduct",
        "imp-p-3": "Users agree to use the platform exclusively for its intended legal purpose. It is strictly prohibited to publish content (posts, chat messages, comments, or images) that:",
        "imp-li-1": "Contains insults, defamation, threats, hate speech, racism, or discrimination.",
        "imp-li-2": "Displays pornographic, sexually explicit (including commercial swimwear/underwear), or youth-endangering imagery.",
        "imp-li-3": "Depicts violence-glorifying, extremist, or unconstitutional material.",
        "imp-li-4": "Violates applicable law (e.g., copyright law, criminal law) or pursues spam or fraudulent intentions.",
        "imp-li-5": "Serves commercial or profit-oriented ticket resale (reselling/scalping). Starting slots may be offered at a maximum of the organizer's official original price.",
        "imp-h3-3": "§ 3 Automated Moderation & Virtual House Rules",
        "imp-p-4": "To ensure the safety, youth protection, and quality of the marketplace, the operator uses automated filters and AI systems for real-time moderation:",
        "imp-li-6": "<strong>Text Filter:</strong> All submitted posts and comments are fully automatically checked against an integrated list of impermissible terms and profanity.",
        "imp-li-7": "<strong>Image AI:</strong> Uploaded image files are scanned via software using artificial intelligence for visual guideline violations (such as nudity or partial nudity).",
        "imp-p-5": "If a post or comment violates these guidelines, the entry will be <span class='highlight'>immediately, fully automatically, and irrevocably deleted without prior warning</span>. The operator reserves the right under its virtual house rules to temporarily or permanently suspend user accounts in the event of violations.",
        "imp-h3-4": "§ 4 Disclaimer of Liability",
        "imp-p-6": "We explicitly assume no liability for:",
        "imp-li-8": "The actual completion of starting slot transfers.",
        "imp-li-9": "The accuracy of match data, deadlines, or prices posted by users in chats or listings.",
        "imp-li-10": "Financial losses or damages caused by fraud or discrepancies between users.",
        "imp-li-11": "The final decision of the respective Match Director (organizer) regarding whether a transfer is accepted.",
        "imp-alert-title": "IMPORTANT NOTICE REGARDING TRANSACTIONS:",
        "imp-alert-desc": "The financial transaction and the final transfer with the Match Director are 100% the responsibility of the respective users. We strongly advise completing payments exclusively via secure methods (e.g., PayPal with buyer protection) and obtaining the organizer's explicit consent BEFORE making a payment.",
        "imp-h2-3": "3. Privacy Policy",
        "imp-p-7": "We take the protection of your personal data very seriously. This privacy policy informs you about the type, scope, and purpose of processing personal data on our platform.",
        "imp-h3-5": "1. Data Controller",
        "imp-p-8": "The controller responsible for data processing is the website operator named in the Legal Notice above.",
        "imp-h3-6": "2. Collection and Processing of User Data",
        "imp-p-9": "To create listings, use the live chat, or contact sellers, you must create a user account. During this process, we collect the following data:",
        "imp-li-12": "<strong>Email Address:</strong> Necessary for login, verification, system notifications, chat message assignment, and contact purposes.",
        "imp-li-13": "<strong>Password:</strong> Stored cryptographically encrypted (no plaintext access for the operator).",
        "imp-li-14": "<strong>Username (Optional):</strong> For display on the platform within your posts.",
        "imp-li-15": "<strong>Chat Messages:</strong> Message histories exchanged within the integrated live chat are stored in the database to provide the chat function.",
        "imp-li-16": "<strong>User-generated Content:</strong> Posted match data, descriptions, prices, comments, and uploaded images.",
        "imp-h3-7": "3. Visibility of Your Data & Live Chat Functionality",
        "imp-p-10": "The core principle of this exchange is the transfer of starting slots. <strong>When you create a listing or use the live chat, the relevant data is visible to the respective chat partners.</strong> Within marketplace listings, your email address is accessible to other logged-in users to enable contact (Art. 6 (1) lit. a and lit. b GDPR).",
        "imp-p-11": "Additionally, a manual function is available in the live chat allowing users to 'nudge' their chat partner via email. This opens the user's local email program via a mailto-link independently; no automated data forwarding to third-party providers takes place in the background via this interface.",
        "imp-h3-8": "4. Automated Content Verification & Data Transmission",
        "imp-p-12": "To protect our legitimate interest in a secure, legally compliant, and disruption-free platform (Art. 6 (1) lit. f GDPR), content is processed as follows:",
        "imp-li-17": "<strong>Image Scans (Sightengine):</strong> When an image is uploaded, its URL is automatically transmitted to the API of the inspection service Sightengine (Sightengine SAS, France/EU). The image is purely machine-analyzed for violations (e.g., nudity filters). No permanent storage or use of the images for third-party purposes or AI training by the service provider occurs.",
        "imp-h3-9": "5. Use of Supabase (Hosting, Data Storage & Live Chat)",
        "imp-p-13": "This website uses the backend service 'Supabase' (Supabase Inc., San Francisco, USA) for the central database, storing chat histories (Live Chat), file storage, and user authentication. Your data is hosted and processed on infrastructures provided by Supabase within the EU (Region: Frankfurt am Main, Germany). We have concluded a legally binding Data Processing Addendum (DPA) with the provider pursuant to Art. 28 GDPR. Further info: <a href='https://supabase.com/privacy' target='_blank' rel='noopener'>Supabase Privacy</a>.",
        "imp-h3-10": "6. Match Analytics & Results Scraper",
        "imp-p-14": "If you enter your real name in your profile settings on our platform, we use automated systems at your explicit request to search publicly accessible internet IPSC tournament result lists for this name. The hits concerning you (such as match name, stage, hit factors) are imported into our database to display your statistics (Art. 6 (1) lit. b GDPR). <strong>Important:</strong> Data of third persons who are also on these lists are only processed fleetingly in the memory of our systems and immediately discarded. No storage or profiling of foreign personal data takes place.",
        "imp-h3-11": "7. Cookies & Local Storage",
        "imp-p-15": "To maintain your login status across browser sessions, Supabase stores an authentication token in the 'Local Storage' of your device. This is a technically strictly necessary process (Art. 6 (1) lit. f GDPR). No marketing, tracking, or advertising cookies are used.",
        "imp-h3-12": "8. Deletion of Data upon Request",
        "imp-p-16": "You can immediately, permanently, and irrevocably remove your entire profile, all your listings, written comments, and your complete personal chat histories from our live database with one click on 'Irrevocably delete account & all entries' in your account settings.",
        "imp-h3-13": "9. Your Rights",
        "imp-p-17": "Under the GDPR, you have the right to free information about your stored data, correction, blocking, or deletion of this data, as well as the right to data portability. Please contact the email address provided in the Legal Notice at any time for this purpose."
    }
};

// Automatischer Übersetzungs-Ablauf für statische Elemente und Input-Platzhalter
window.translatePortalPage = function() {
    const lang = localStorage.getItem("selectedLanguage") || "de";
    window.currentLang = lang;
    
    // 1. Standard-Labels übersetzen
    document.querySelectorAll("[data-txt]").forEach(el => {
        const key = el.getAttribute("data-txt");
        if (window.portalTranslations[lang] && window.portalTranslations[lang][key]) {
            el.innerHTML = window.portalTranslations[lang][key];
        }
    });

    // 2. Input-Platzhalter übersetzen
    document.querySelectorAll("[data-txt-ph]").forEach(el => {
        const key = el.getAttribute("data-txt-ph");
        if (window.portalTranslations[lang] && window.portalTranslations[lang][key]) {
            el.placeholder = window.portalTranslations[lang][key];
        }
    });
    
    if (typeof window.onLanguageChanged === "function") {
        window.onLanguageChanged();
    }
};

window.translations = window.portalTranslations;

document.addEventListener("change", (e) => {
    if (e.target && e.target.id === "language-select") {
        localStorage.setItem("selectedLanguage", e.target.value);
        window.translatePortalPage();
    }
});

if (document.readyState === 'loading') {
    document.addEventListener('DOMContentLoaded', window.translatePortalPage);
} else {
    window.translatePortalPage();
}
