// Zentrale Übersetzungs-Datenbank für das gesamte IPSC-Portal
window.portalTranslations = {
    de: {
        // --- GEMEINSAME ELEMENTE & HEADER/FOOTER ---
        "main-title": "IPSC STARTPLATZ-BÖRSE",
        "sub-title": "Von Schützen für Schützen",
        "btn-login-reg": "Login / Registrieren",
        "logout": "Abmelden",
        "footer-impressum-link": "Impressum & Rechtliche Hinweise",
        "buy-coffee": "Kaffee spendieren",
        "btn-save": "Speichern",

        // --- NAVIGATION KEYS ---
        "nav-startseite": "Startseite",
        "nav-wiederladen": "Wiederladen",
        "nav-analytics": "Statistiken",
        "nav-sgtimer": "⏱️ SG-Timer Live",
        "sg-timer-archive-title": "Timer archive",
        "sg-timer-device-archive": "Timer archive",
        "sg-timer-highscores-title": "🏆 Global drill leaderboards",
        "sg-timer-archive-desc": "Search your SG Timer’s internal memory and import stored runs directly into your training log.",
        "sg-timer-connection": "Connection",
        "sg-timer-highscores": "🏆 Global highscores",
        "sg-timer-archive-title": "Timer-Archiv",
        "sg-timer-device-archive": "Timer-Archiv",
        "sg-timer-highscores-title": "🏆 Globale Drill-Bestenlisten",
        "sg-timer-archive-desc": "Durchsuche den internen Speicher deines SG-Timers und übernimm gespeicherte Durchgänge direkt in dein Trainingstagebuch.",
        "sg-timer-connection": "Verbindung",
        "sg-timer-highscores": "🏆 Global Highscores",
        "tab-start": "Home",
        "tab-market": "Market",
        "tab-planner": "Planner",
        "tab-comm": "Comm",
        "tab-more": "More",
        "chat-loading": "Lade Chat-Verlauf...",
        "chat-send": "Senden",
        "chat-input-placeholder": "Nachricht schreiben...",
        "chat-open-inbox": "Nachrichten öffnen",
        "chat-notification-body": "Du hast eine neue Chat-Nachricht erhalten.",
        "chat-notification-title": "Neue Nachricht",
        "community-comment-placeholder": "Schreibe einen Kommentar...",
        "community-comments-loading": "Lade Kommentare...",
        "community-send": "Senden",
        "community-report": "Melden",
        "community-comment": "Kommentieren",
        "tab-start": "Start",
        "tab-market": "Markt",
        "tab-planner": "Planer",
        "tab-comm": "Comm",
        "tab-more": "Mehr",
        "card-title-schiessbuch": "Schießbuch",

        // --- STARTSEITE (index.html) ---
        "hero-title": "DVC – Willkommen auf deiner IPSC-Plattform",
        "hero-desc": "Die zentrale Anlaufstelle für IPSC-Schützen im deutschsprachigen Raum. Tausche Startplätze, finde freie Match-Plätze, diskutiere in der Community oder nutze unsere interaktiven Trainingstools.",
        "news-title": "📢 Neueste Plattform-Updates",
        "tab-start": "Start",
        "tab-market": "Markt",
        "tab-planner": "Planer",
        "tab-comm": "Comm",
        "tab-more": "Mehr",
        "news-date-appstore": "Demnächst",
        "news-heading-appstore": "📱 AppStore Beta Launch",
        "news-body-appstore": "Die Beta-Phase für unsere native Smartphone-App steht kurz bevor! Demnächst startet der offizielle Testlauf im Apple App Store und Google Play Store. Mach dich bereit für echte Push-Benachrichtigungen und flüssigere Hardware-Integrationen direkt auf deinem Handy.",
        "news-date-schiessbuch": "Juni 2026",
        "news-heading-schiessbuch": "📋 Digitales Schießbuch (12/18 Nachweis)",
        "news-body-schiessbuch": "Führe dein Schießbuch ab sofort komplett digital und manipulationssicher. Lass dir deine Trainingseinheiten direkt auf der Range von der Standaufsicht per Touchscreen abzeichnen und generiere dein verifiziertes PDF-Protokoll fürs Amt mit nur einem Klick.",
        "news-date-sgtimer-live": "Juni 2026",
        "news-heading-sgtimer-live": "⏱️ SG-Timer Live-Integration",
        "news-body-sgtimer-live": "Verbinde deinen Shooters Global Timer kabellos via Bluetooth direkt mit der Plattform. Verfolge deine Splits in Echtzeit, steuere dein Gerät per RO-Fernbedienung und trage deine Zeiten direkt in unsere globalen Highscores ein.",
        "news-date-reload": "Juni 2026",
        "news-heading-reload": "📦 Neue Sektion: Wiederladen-Datenbank",
        "news-body-reload": "Die Wiederladen-Ecke ist ab sofort live! Speichere deine bewährten Laborierungen, Pulvermengen und OAL-Werte ab sofort sicher in deiner persönlichen Cloud ab und greife von der Range aus jederzeit darauf zu.",
        "news-date-1": "Juni 2026",
        "news-heading-1": "📱 Die IPSC-Börse als echte App (PWA)",
        "news-body-1": "Wir haben die Plattform 'App-ready' gemacht! Du kannst die Seite jetzt ganz einfach über deinen mobilen Browser (Safari/Chrome) über 'Zum Home-Bildschirm hinzufügen' als vollwertige App auf deinem Smartphone installieren – inklusive schickem IPSC-Scheiben-Icon.",
        "news-date-2": "Mai 2026",
        "news-heading-2": "⏱️ Neue Sektion: Tools & Training integriert",
        "news-body-2": "Ab sofort stehen dir mächtige Trainingshelfer zur Verfügung. Berechne präzise deinen Hit-Factor direkt auf der Range oder nutze unseren reaktionsschnellen Dry-Fire-Timer für dein Trockentraining zu Hause.",
        "news-date-3": "April 2026",
        "news-heading-3": "🛡️ 'Trusted Shooter' Reputationssystem",
        "news-body-3": "Um die Sicherheit auf dem Marktplatz zu maximieren, wurde ein Reputationssystem eingeführt. Durch Hinterlegen du deines IPSC-Alias erhältst du ein verifiziertes Abzeichen, zudem können erfolgreiche Vermittlungen gegenseitig bewertet werden.",
        "card-title-market": "Marktplatz",
        "card-desc-market": "Suche nach verfügbaren Startplätzen für ausgebuchte Matches oder biete dein eigenes Ticket zum Tausch an.",
        "card-action-market": "Zum Marktplatz &rarr;",
        "card-title-free": "Matches",
        "card-desc-free": "Live-Auslastungs-Tracker für MatchSign. Finde sofort Turniere, die aktuell noch freie Plätze aufweisen.",
        "card-action-free": "Freie Plätze prüfen &rarr;",
        "card-title-planer": "Mein Planer",
        "card-desc-planer": "Plane deine perfekte IPSC-Saison, halte Fristen im Auge und exportiere deine Matches direkt in deinen Kalender.",
        "card-action-planer": "Saison planen &rarr;",
        "card-title-comm": "Community",
        "card-desc-comm": "Vernetze dich mit anderen Schützen, diskutiere über Ausrüstung und teile Beiträge im sozialen Feed.",
        "card-action-comm": "Zur Community &rarr;",
        "card-title-hub": "IPSC Hub",
        "card-desc-hub": "Schluss mit Suchen: Alle wichtigen Links zu MatchSign, PractiScore, IPSCess, Verbänden und Regelwerken gebündelt.",
        "card-action-hub": "Zum Link-Hub &rarr;",
        "card-title-tools": "Tools & Training",
        "card-desc-tools": "Interaktiver Hit-Factor-Rechner, Stage-Planungs-Assistent und ein konfigurierbarer Dry-Fire-Timer für dein Training.",
        "card-action-tools": "Zu den Tools &rarr;",

        // --- KONTO-EINSTELLUNGEN MODAL (ALLE SEITEN) ---
        "modal-settings-title": "Konto",
        "modal-settings-deals": "📈 Erfolgreiche Vermittlungen",
        "modal-settings-seller": "Als Verkäufer",
        "modal-settings-buyer": "Als Käufer",
        "modal-settings-comm": "💬 Kommunikation:",
        "modal-settings-pay": "💳 Bezahlung:",
        "modal-settings-passkey-title": "🔒 Passkey (Schnell-Login)",
        "modal-settings-passkey-desc": "Hinterlege dein aktuelles Gerät, um dich künftig ohne Passwort per FaceID, Fingerabdruck oder PIN einzuloggen.",
        "modal-settings-passkey-btn": "Gerät als Passkey registrieren",
        "lbl-username": "Schützenname / Anzeigename",
        "lbl-ipsc-alias": "🛡️ IPSC Alias / Mitgliedsnummer",
        "lbl-ipsc-alias-desc": "Optional. Nicht öffentlich. Nur für interne Zuordnung und geschützte Vereinsfunktionen.",
        "lbl-real-name": "🔒 Echter Name (für automatische Zuordnung)",
        "lbl-real-name-desc": "Trage deinen Namen so ein, wie er in Starterlisten erscheint. Der Name wird nicht öffentlich angezeigt und hilft der App, öffentlich verfügbare Matchdaten korrekt zuzuordnen.",
        "ph-real-name": "z.B. Max Mustermann",
        "lbl-profile-pic": "Profilbild (Optional)",
        "lbl-change-password": "Neues Passwort (optional)",
        "btn-delete-acc": "Konto & alle Einträge unwiderruflich löschen",
        
        // --- PLATZHALTER-ÜBERSETZUNGEN ---
        "ph-username": "z.B. IPSCShooter99",
        "ph-ipsc-alias": "z.B. GER1234 (Optional)",
        "ph-password": "Mindestens 6 Zeichen (Unverändert lassen für keine Änderung)",

        // --- MARKTPLATZ STATIC ELEMENTS (marktplatz.html) ---
        "info-msg": "<strong>Wichtiger Hinweis:</strong> Diese Plattform dient nur der Vermittlung. Die endgültige Umschreibung des Startplatzes muss zwingend über den jeweiligen Match Director durchgeführt werden!",
        "form-title": "Eintrag erstellen",
        "opt-offer": "Ich BIETE einen Startplatz an",
        "opt-want": "Ich SUCHE einen Startplatz",
        "lbl-name": "Name des Matches *",
        "lbl-level": "Match Level *",
        "lbl-date": "Datum des Matches *",
        "lbl-country": "Land *",
        "lbl-location": "Austragungsort (Stand) *",
        "lbl-squad": "Squad Nummer (Optional)",
        "lbl-price": "Abgabepreis (€) *",
        "lbl-email": "Deine E-Mail-Adresse *",
        "btn-cancel": "Abbrechen",
        "btn-insert": "Eintrag kostenlos veröffentlichen",
        "filter-type": "Anzeigentyp:",
        "filter-all": "Alle Anzeigen",
        "filter-offers": "Nur Angebote (Biete)",
        "filter-wants": "Nur Gesuche (Suche)",
        "list-title": "Aktuelle Marktplatz-Einträge",
        "loading": "Lade aktuelle Startplätze...",

        "market-form-kicker": "Startplatz-Börse",
        "market-form-title": "Eintrag erstellen",
        "market-form-text": "Startplatz anbieten oder suchen",
        "planner-form-kicker": "Match-Planer",
        "planner-form-title": "Match erstellen",
        "planner-form-text": "Neues Match in deine Saisonplanung aufnehmen",
        "label-squad": "Squad",
        "listed-by": "Inseriert von",
        "trusted-badge": "Trusted",
        "trusted-title": "Verifizierter IPSC Alias",
        "btn-live-chat": "Live-Chat",
        "btn-mediated": "Vermittelt",

        // --- MARKTPLATZ ERWEITERTE POPUPS ---
        "mediated-title": "Startplatz erfolgreich vermittelt",
        "mediated-desc": "Trage hier die E-Mail-Adresse des Käufers ein und bewerte die Transaktion, um sie abzuschließen. Die erfolgreiche Vermittlung wird in euren Profilstatistiken hinterlegt.",
        "lbl-buyer-email": "E-Mail-Adresse des Käufers *",
        "lbl-rating-comm": "💬 Kommunikation",
        "lbl-rating-pay": "💳 Bezahlung",
        "btn-mediated-submit": "Vermittlung bestätigen & Eintrag schließen",

        // --- MARKTPLATZ DYNAMIC TEXTS (app.js) ---
        "no-slots": "Aktuell keine Einträge verfügbar.",
        "btn-request": "Anbieter kontaktieren",
        "btn-contact-want": "Schützen kontaktieren",
        "btn-delete": "Löschen",
        "btn-edit": "Bearbeiten",
        "btn-manage": "Verwalten",
        "btn-export": "Export (.ics)",
        "report-btn": "Melden",
        "form-title-edit": "Eintrag bearbeiten ✏️",
        "btn-save-edit": "Änderungen speichern",
        "login-required": "Nur eingeloggte Nutzer können Schützen kontaktieren.",
        "tag-offer": "BIETE",
        "tag-want": "SUCHE",
        "spam-error": "Spam-Schutz: Du hast bereits einen Eintrag für dieses Match an diesem Datum erstellt!",
        "email-subject-offer": "Interesse an deinem IPSC Startplatz: ",
        "email-subject-want": "Bezüglich deiner Suche nach einem IPSC Startplatz: ",
        "email-body-offer": "Hallo,\n\ ich habe dein Inserat auf ipscboerse.com gesehen und interessiere mich für den von dir angebotenen Startplatz für das Match: ",
        "email-body-want": "Hallo,\n\ ich habe dein Gesuch auf ipscboerse.com gesehen. Ich hätte einen Startplatz abzugeben für das Match: ",
        "email-body-footer": "\n\nIst das Inserat noch aktuell?\n\nViele Grüße",
        "security-checklist": "\n\nSicherheits-Checkliste vor der E-Mail:\n- Match-Daten geprüft?\n- Match Director kontaktiert?",
        "security-notice": "⚠️ WICHTIGER SICHERHEITSHINWEIS:\n\n1. Nutze für Zahlungen IMMER PayPal mit Käuferschutz (niemals 'Freunde & Familie').\n2. Kontaktiere ZWINGEND den Match Director, BEVOR du Geld sendest, um zu prüfen, ob eine Umschreibung des Platzes überhaupt noch möglich ist!\n\nMöchtest du den E-Mail-Kontakt jetzt öffnen?",

        // --- FREIE MATCH-PLÄTZE (freie-matches.html) ---
        "free-info-box": "<strong>Info:</strong> Die Matches werden automatisch im Hintergrund aktualisiert. Es werden nur Turniere angezeigt, die eine Auslastung von unter 100% aufweisen (freie Startplätze).",
        "free-list-title": "Verfügbare Matches auf MatchSign (Auslastung < 100%)",
        "free-loading": "Lade aktuelle Matches...",

        // --- WETTKAMPFPLANER (mein-planer.html) ---
        "planner-logged-out-title": "Nicht angemeldet",
        "planner-logged-out-desc": "Logge dich ein, um deine Matches zu verwalten und in die Cloud zu synchronisieren.",
        "planner-logged-out-btn": "Jetzt einloggen",
        "planner-title-my-matches": "Meine Matches",
        "planner-subtitle-new": "Neuer Eintrag",
        "log-entry-title": "Neuer Eintrag",
        "log-entry-save": "Eintrag speichern",
        "planner-lbl-match-name": "Match-Name",
        "planner-lbl-match-date": "Datum",
        "planner-lbl-match-location": "Adresse / Ort / Land",
        "planner-btn-save": "Eintrag speichern",
        "planner-subtitle-planned": "Geplante Matches",
        "planner-loading": "Lade Daten aus Supabase...",
        "planner-btn-export": "📅 In Kalender exportieren (.ics)",
        "planner-no-matches": "Noch keine Matches eingetragen.",

        // --- COMMUNITY (community.html) ---
        "tab-posts": "Beiträge",
        "tab-groups": "Gruppen",
        "comm-logged-out-title": "Werde Teil der Community",
        "comm-logged-out-desc": "Bitte logge dich ein, um Beiträge zu lesen und mit anderen Schützen zu diskutieren.",
        "comm-logged-out-btn": "Jetzt einloggen",
        "comm-setup-title": "Wähle deinen Schützennamen",
        "comm-setup-desc": "Bevor du in der Community starten kannst, wähle bitte einen Schützennamen / Anzeigenamen (z.B. IPSCShooter99).",
        "comm-setup-btn": "Namen speichern & starten",
        "comm-loading": "Lade Beiträge...",
        "fab-create-post": "+ Beitrag erstellen",
        "comm-groups-coming": "Gruppen-Funktion (Coming Soon)",
        "comm-groups-desc": "Hier wirst du bald private Squad-Gruppen oder Vereins-Kanäle erstellen können.",
        "modal-new-post": "Neuer Beitrag",
        "lbl-add-photo": "Foto hinzufügen (Optional)",
        "btn-share-post": "Teilen",

        // --- LOGIN & AUTH MODALS ---
        "modal-login-title": "Anmelden",
        "link-forgot-pwd": "Passwort vergessen?",
        "modal-btn-login": "Mit Passwort einloggen",
        "modal-social-separator": "Oder Schnell-Login nutzen:",
        "modal-passkey-login": "Mit Face ID / Passkey fortfahren",
        "modal-apple-login": "Mit Apple anmelden",
        "modal-google-login": "Mit Google anmelden",
        "lbl-password": "Passwort *",
        "modal-no-acc": "Noch kein Konto?",
        "modal-link-reg": "Registrieren",
        "modal-reg-title": "Konto erstellen",
        "modal-has-acc": "Bereits registriert?",
        "modal-link-login": "Zum Login",
        "modal-forgot-title": "Passwort vergessen",
        "modal-btn-forgot": "Zurücksetzungs-Link senden",
        "modal-reset-title": "Neues Passwort vergeben",
        "lbl-new-password": "Neues Passwort *",

        // --- TOOLS (tools.html) ---
        "tools-hf-title": "🏆 Hit-Factor Battle",
        "tools-hf-desc": "Trage die Ergebnisse von dir und deinen Freunden ein, um eine Live-Rangliste für die Stage zu erstellen.",
        "tools-hf-name": "Schützenname",
        "tools-hf-pf": "Wertung",
        "tools-hf-time": "Zeit (Sek.)",
        "tools-hf-scoring": "Trefferaufnahme",
        "tools-hf-alpha": "Alpha (A)",
        "tools-hf-charlie": "Charlie (C)",
        "tools-hf-delta": "Delta (D)",
        "tools-hf-miss": "Miss (M)",
        "tools-hf-ns": "No-Shoot",
        "tools-hf-proc": "Procedure",
        "tools-hf-btn-submit": "Schütze eintragen & berechnen",
        "tools-th-name": "Name",
        "tools-th-pts": "Pts",
        "tools-th-time": "Zeit",
        "tools-th-hf": "HF",
        "tools-hf-btn-clear": "Rangliste leeren",
        "tools-df-title": "⏱️ Dry-Fire Timer & Drill Generator",
        "tools-df-placeholder": "Klicke auf den Button, um einen zufälligen Trockentrainings-Ablauf zu generieren.",
        "tools-df-btn-gen": "🎲 Neuen Drill generieren",
        "tools-df-par": "Par-Zeit (Sekunden)",
        "tools-df-status-ready": "Bereit",
        "tools-df-btn-start": "Start Timer (Zufalls-Delay)",
        "tools-pf-title": "⏱️ IPSC Power-Factor Manager",
        "tools-pf-desc": "Berechne den Power Factor deiner Laborierung und überprüfe den Status für das Match.",
        "tools-pf-weight": "Geschossgewicht (Grains)",
        "tools-pf-velocity": "Geschwindigkeit (fps)",
        "tools-pf-target": "Angestrebte Wertung",
        "tools-pf-opt-minor": "Minor (Mindest-Faktor 125)",
        "tools-pf-opt-major": "Major (Mindest-Faktor 160)",
        "tools-pf-result-label": "Errechneter Power Factor",
        "tools-db-title": "📦 Meine Wiederlade-Rezepte",
        "tools-db-desc": "Speichere deine bewährten Laborierungen dauerhaft in deiner Cloud ab.",
        "tools-db-logged-out": "Logge dich ein, um deine persönliche Wiederlade-Datenbank zu nutzen und Rezepte in der Cloud zu speichern.",
        "tools-db-caliber": "Kaliber",
        "tools-db-bullet-type": "Geschosstyp / Hersteller",
        "tools-db-bullet-type-ph": "z.B. LOS HP oder H&N HS",
        "tools-db-powder": "Pulver (Sorte & Menge)",
        "tools-db-powder-ph": "z.B. 3.7gr N320",
        "tools-db-oal": "OAL (mm)",
        "tools-db-oal-ph": "z.B. 29.00",
        "tools-db-notes": "Notizen / Waffe (Optional)",
        "tools-db-notes-ph": "z.B. Sicherer Minor-Faktor aus CZ Shadow 2",
        "tools-db-btn-save": "💾 Rezept in Cloud speichern",
        "tools-db-saved-title": "Ladedaten",

        // --- IPSC HUB ---
        "hub-main-title": "IPSC Hub – Alle wichtigen Links",
        "hub-main-desc": "Schluss mit dem ewigen Suchen: Hier findest du zentral gebündelt alle wichtigen Plattformen für Match-Anmeldungen, Ergebnisse und Verbandsinfos rund um unser Hobby.",
        "hub-cat-management": "🎯 Match-Anmeldungen & Verwaltung",
        "hub-desc-matchsign": "Die bekannteste und meistgenutzte Plattform für IPSC Match-Anmeldungen in Deutschland.",
        "hub-btn-matchsign": "Zu MatchSign",
        "hub-desc-ipscess": "Offizielles Portal für die Verwaltung von Lizenzen, Matchpunkten und dem IPSC-Ausweis.",
        "hub-btn-ipscess": "Zum IPSCess Portal",
        "hub-desc-practiscore": "Das internationale System. Unverzichtbar für ausländische Matches und Live-Scoring vor Ort.",
        "hub-btn-practiscore": "Zu PractiScore",
        "hub-desc-makeready": "Häufig genutzt für große internationale Turniere und Matches im europäischen Umland.",
        "hub-btn-makeready": "Zu MakeReady",
        "hub-cat-stats": "📊 Statistiken & Rankings",
        "hub-desc-ipscelo": "Inoffizielles, aber fantastisches Elo-Ranking und Statistik-Tool basierend auf internationalen Match-Ergebnissen.",
        "hub-btn-ipscelo": "Zu IPSCelo",
        "hub-cat-rules": "📖 Verbände & Regelwerke",
        "hub-desc-bds": "Der Bund Deutscher Sportschützen. Offizielle Anlaufstelle für Sportordnung, Befürwortungen und Termine.",
        "hub-btn-bds": "Zum BDS",
        "hub-desc-rules": "Die aktuellen internationalen Regelwerke (Handgun, Rifle, PCC, Shotgun) direkt als PDF zum Download.",
        "hub-btn-rules": "Zu den Rulebooks",

        // --- PERFORMANCE ANALYTICS & DASHBOARD ---
        "analytics-title": "🏆 IPSC Performance Analytics",
        "analytics-desc": "Überwache deine sportliche Entwicklung, deine Treffer-Präzision und deine Hit-Factor-Trends der letzten Matches.",
        "analytics-kpi-matches": "Matches Gesamt",
        "analytics-kpi-avg-hf": "Ø Hit Factor",
        "analytics-chart-title": "📈 Hit-Factor Trend (Letzte 5 Stages)",
        "analytics-acc-title": "🎯 Treffer-Verteilung (Präzision)",
        "analytics-box-title": "📧 A, C, D automatisch eintragen",
        "analytics-box-desc": "Ergebnisse und Hitfaktor werden automatisch geladen. Wer auch <strong>A, C, D und Misses</strong> automatisch drin haben will, leitet seine PractiScore-Mails nach dem Match einfach an <strong style='color: var(--text-color);'>info@ipscboerse.com</strong> weiter!",

        // --- IMPRESSUM & RECHTLICHES (DE) ---
        "imp-back": "← Zurück zur Startseite",
        "imp-h2-1": "1. Impressum",
        "imp-p-1": "<strong>Angaben gemäß § 5 TMG:</strong><br>Fabian Schöps<br>Weserblick 9<br>34399 Wesertal",
        "imp-p-contact": "<strong>Kontakt:</strong><br>E-Mail: <a href='mailto:info@ipscboerse.com'>info@ipscboerse.com</a>",
        "imp-h2-2": "2. Allgemeine Geschäftsbedingungen (AGB) & Nutzungsbedingungen",
        "imp-h3-1": "§ 1 Geltungsbereich und Zweck der Plattform",
        "imp-p-2": "Die Plattform (ipscboerse.com) stellt ausschließlich eine technische Infrastruktur zur Verfügung (\"Schwarzes Brett\"), um Sportschützen untereinander zur Vermittlung von Startplätzen zu vernetzen. Der Betreiber dieser Webseite tritt <strong>nicht</strong> als Veranstalter, Käufer, Verkäufer oder offizieller Vermittler von Startplätzen auf. Verträge über den Startplatztausch kommen ausschließlich zwischen den beteiligten Nutzern zustande.",
        "imp-h3-2": "§ 2 Pflichten der Nutzer & Verhaltensregeln",
        "imp-p-3": "Nutzer verpflichten sich, die Plattform ausschließlich für den vorgesehenen legalen Zweck zu nutzen. Es ist strengstens untersagt, Inhalte (Beiträge, Chat-Nachrichten, Kommentare oder Bilder) zu veröffentlichen, die:",
        "imp-li-1": "Beleidigungen, Verleumdungen, Bedrohungen, Hate Speech, Rassismus oder Diskriminierungen enthalten.",
        "imp-li-2": "Pornografische, sexuell anstößige (einschließlich kommerzieller Bademode/Unterwäsche) oder jugendgefährdende Motive zeigen.",
        "imp-li-3": "Gewaltverherrlichendes, extremistisches oder verfassungsfeindliches Material darstellen.",
        "imp-li-4": "Gegen geltendes Recht (z.B. Urheberrecht, Strafrecht) verstoßen oder Spam bzw. betrügerische Absichten verfolgen.",
        "imp-li-5": "Dem gewerblichen oder gewinnorientierten Ticket-Weiterverkauf (Reselling/Scalping) dienen. Startplätze dürfen maximal zum offiziellen Originalpreis des Veranstalters angeboten werden.",
        "imp-h3-3": "§ 3 Automatisierte Moderation & Hausrecht",
        "imp-p-4": "Um die Sicherheit, Jugendfreiheit und Qualität des Marktplatzes zu gewährleisten, setzt der Betreiber automatisierte Filter- und KI-Systeme zur Echtzeit-Moderation ein:",
        "imp-li-6": "<strong>Text Filter:</strong> Alle eingestellten Beiträge und Kommentare werden vollautomatisch auf eine integrierte Liste unzulässiger Begriffe und Schimpwörter geprüft.",
        "imp-li-7": "<strong>Bild KI:</strong> Hochgeladene Bilddateien werden softwareseitig mittels künstlicher Intelligenz auf visuelle Richtlinienverstöße (wie z.B. Nacktheit oder Teilnacktheit) gescannt.",
        "imp-p-5": "Verstört ein Beitrag oder Kommentar gegen diese Richtlinien, wird der Eintrag durch das System <span class='highlight'>sofort, vollautomatisch und ohne Vorwarnung unwiderruflich gelöscht</span>. Der Betreiber behält sich im Rahmen seines Hausrechts das Recht vor, Nutzerkonten bei Verstößen temporär oder dauerhaft zu sperren.",
        "imp-h3-4": "§ 4 Haftungsausschluss (Disclaimer)",
        "imp-p-6": "Wir übernehmen ausdrücklich keine Haftung für:",
        "imp-li-8": "Das tatsächliche Zustandekommen von Startplatz-Übertragungen.",
        "imp-li-9": "Die Richtigkeit der von Nutzern im Chat oder in Inseraten eingestellten Match-Daten, Fristen oder Preise.",
        "imp-li-10": "Finanzielle Verluste oder Schäden durch Betrug oder Unstimmigkeiten zwischen Nutzern.",
        "imp-li-11": "Die finale Entscheidung des jeweiligen Match Directors (Veranstalters), ob eine Umschreibung akzeptiert wird.",
        "imp-alert-title": "WICHTIGER HINWEIS ZUR ABWICKLUNG:",
        "imp-alert-desc": "Die finanzielle Abwicklung und die finale Umschreibung beim Match Director obliegen zu 100 % der Verantwortung der jeweiligen Nutzer. Wir raten dringend dazu, Zahlungen ausschließlich über sichere Methoden (z. B. PayPal mit Käuferschutz) abzuwickeln und VOR einer Zahlung die ausdrückliche Zustimmung des Veranstalters einzuholen.",
        "imp-h2-3": "3. Datenschutzerklärung",
        "imp-p-7": "Wir nehmen den Schutz deiner persönlichen Daten sehr ernst. Diese Datenschutzerklärung klärt dich über die Art, den Umfang und Zweck der Verarbeitung von personenbezogenen Daten auf unserer Plattform auf.",
        "imp-h3-5": "1. Verantwortlicher für die Datenverarbeitung",
        "imp-p-8": "Verantwortlich für die Datenverarbeitung ist der oben im Impressum genannte Betreiber dieser Webseite.",
        "imp-h3-6": "2. Erfassung und Verarbeitung von Nutzerdaten",
        "imp-p-9": "Um Inserate zu erstellen, den Live-Chat zu nutzen oder Anbieter zu kontaktieren, musst du ein Benutzerkonto anlegen. Dabei erfassen wir folgende Daten:",
        "imp-li-12": "<strong>E-Mail-Adresse:</strong> Notwendig für den Login, die Verifizierung, Systembenachrichtigungen, die Zuordnung von Chat-Nachrichten und die Kontaktaufnahme.",
        "imp-li-13": "<strong>Passwort:</strong> Wird kryptografisch verschlüsselt gespeichert (kein Klartextzugriff für den Betreiber).",
        "imp-li-14": "<strong>Benutzername (Optional):</strong> Zur Darstellung auf der Plattform innerhalb deiner Beiträge.",
        "imp-li-15": "<strong>Chat-Nachrichten:</strong> Im Rahmen des integrierten Live-Chats ausgetauschte Nachrichtenverläufe werden zur Bereitstellung der Chat-Funktion in der Datenbank gespeichert.",
        "imp-li-16": "<strong>Nutzergenerierte Inhalte:</strong> Eingestellte Match-Daten, Beschreibungen, Preise, Kommentare sowie hochgeladene Bilder.",
        "imp-h3-7": "3. Sichtbarkeit deiner Daten & Funktionsweise des Live-Chats",
        "imp-p-10": "Das Kernprinzip dieser Börse ist die Vermittlung von Startplätzen. <strong>Wenn du ein Inserat erstellst oder den Live-Chat nutzt, sind die beteiligten Daten für die jeweiligen Chat-Partner einsehbar.</strong> Innerhalb der Marktplatz-Inserate ist deine E-Mail-Adresse für andere eingeloggte Nutzer abrufbar, um die Kontaktaufnahme zu ermöglichen (Art. 6 Abs. 1 lit. a und lit. b DSGVO).",
        "imp-p-11": "Zusätzlich steht im Live-Chat eine manuelle Funktion zur Verfügung, mit der Nutzer ihren Chat-Partner per E-Mail anstupsen können. Hierbei öffnet sich das lokale E-Mail-Programm des Nutzers via Mailto-Link autark; es findet über diese Schnittstelle keine automatisierte Datenweiterleitung im Hintergrund an Drittanbieter statt.",
        "imp-h3-8": "4. Automated Content Verification & Data Transmission",
        "imp-p-12": "Zur Wahrung unseres berechtigten Interesses an einer sicheren, gesetzeskonformen und störungsfreien Plattform (Art. 6 Abs. 1 lit. f DSGVO) werden Inhalte wie folgt verarbeitet:",
        "imp-li-17": "<strong>Bild-Scans (Sightengine):</strong> Beim Hochladen eines Bildes wird dessen URL automatisiert an die Programmierschnittstelle des Prüfdienstes Sightengine (Sightengine SAS, Frankreich/EU) übermittelt. Das Bild wird dort rein maschinell auf Verstöße (z.B. Filter für Nacktheit) analysiert. Es findet keine dauerhafte Speicherung oder Nutzung der Bilder für Drittzwecke oder KI-Training durch den Dienstleister statt.",
        "imp-h3-9": "5. Nutzung von Supabase (Hosting, Datenspeicherung & Live-Chat)",
        "imp-p-13": "Diese Webseite nutzt für die zentrale Datenbank, das Speichern von Chat-Verläufen (Live-Chat), die Datei-Speicherung (Storage) und die Nutzer-Authentifizierung den Backend-Dienst „Supabase“ (Supabase Inc., San Francisco, USA). Deine Daten werden auf den von Supabase bereitgestellten Infrastrukturen innerhalb der EU (Region: Frankfurt am Main, Deutschland) gehostet und verarbeitet. Wir haben mit dem Anbieter einen rechtskräftigen Vertrag zur Auftragsverarbeitung (Data Processing Addendum, DPA) gemäß Art. 28 DSGVO abgeschlossen. Weitere Infos: <a href='https://supabase.com/privacy' target='_blank' rel='noopener'>Supabase Privacy</a>.",
        "imp-h3-10": "6. Match-Analytics & Ergebnis-Scraper",
        "imp-p-14": "Wenn du auf unserer Plattform deinen echten Namen in den Profileinstellungen hinterlegst, nutzen wir auf deine ausdrückliche Anforderung hin automatisierte Systeme, um öffentlich zugängliche Ergebnislisten von IPSC-Turnieren im Internet nach diesem Namen zu durchsuchen. Die gefundenen, dich betreffenden Trefferdaten (wie Matchname, Stage, Faktoren) werden in unsere Datenbank importiert, um dir deine Statistiken anzuzeigen (Art. 6 Abs. 1 lit. b DSGVO). <strong>Wichtig:</strong> Daten dritter Personen, die sich ebenfalls auf diesen Listen befinden, werden von unseren Systemen lediglich flüchtig im Arbeitsspeicher verarbeitet und sofort verworfen. Es findet keinerlei Speicherung oder Profilbildung fremder Personendaten statt.",
        "imp-h3-11": "7. Cookies & Local Storage",
        "imp-p-15": "Um deinen Login-Status über Browsersitzungen hinweg aufrechtzuerhalten, speichert Supabase ein Authentifizierungs-Token im 'Local Storage' deines Endgeräts. Dies ist ein technisch zwingend notwendiger Vorgang (Art. 6 Abs. 1 lit. f DSGVO). Es werden keine Marketing-, Tracking- oder Werbe-Cookies eingesetzt.",
        "imp-h3-12": "8. Ergebnisbezogene Löschung von Daten",
        "imp-p-16": "Du kannst in deinen Konto mit einem Klick auf 'Konto & alle Einträge unwiderruflich löschen' dein gesamtes Profil, all deine Inserate, verfassten Kommentare sowie deine gesamten persönlichen Chat-Verläufe sofort, dauerhaft und unwiderruflich aus unserer Live-Datenbank entfernen.",
        "imp-h3-13": "9. Deine Rechte",
        "imp-p-17": "Nach der DSGVO hast du das Recht auf unentgeltliche Auskunft über deine gespeicherten Daten, Berichtigung, Sperrung oder Löschung dieser Daten sowie das Recht auf Datenübertragbarkeit. Wende dich hierfür jederzeit an die im Impressum angegebene E-Mail-Adresse."
    },
    en: {
        // --- COMMON ELEMENTS & HEADER/FOOTER ---
        "main-title": "IPSC SLOT MARKETPLACE",
        "sub-title": "By Shooters for Shooters",
        "btn-login-reg": "Login / Register",
        "logout": "Logout",
        "footer-impressum-link": "Legal Notice & Disclaimers",
        "buy-coffee": "Buy me a coffee",
        "btn-save": "Save Changes",

        // --- NAVIGATION KEYS ---
        "nav-startseite": "Home",
        "nav-wiederladen": "Reloading",
        "nav-analytics": "Analytics",
        "nav-sgtimer": "⏱️ SG-Timer Live",
        "card-title-schiessbuch": "Shooting Log",

        // --- HOME PAGE (index.html) ---
        "hero-title": "DVC – Welcome to your IPSC Platform",
        "hero-desc": "The central hub for IPSC shooters in the German-speaking region. Exchange starting slots, find available match slots, discuss in the community or use our interactive training tools.",
        "news-title": "📢 Latest Platform Updates",
        "tab-start": "Home",
        "tab-market": "Market",
        "tab-planner": "Planner",
        "tab-comm": "Comm",
        "tab-more": "More",
        "chat-loading": "Loading messages...",
        "chat-send": "Send",
        "chat-input-placeholder": "Write a message...",
        "chat-open-inbox": "Open messages",
        "chat-notification-body": "You received a new chat message.",
        "chat-notification-title": "New message",
        "community-comment-placeholder": "Write a comment...",
        "community-comments-loading": "Loading comments...",
        "community-send": "Send",
        "community-report": "Report",
        "community-comment": "Comment",
        "news-date-appstore": "Coming soon",
        "news-heading-appstore": "📱 App Store Beta Launch",
        "news-body-appstore": "The beta phase for our native smartphone app is just around the corner. The official test run in the Apple App Store and Google Play Store will start soon. Get ready for real push notifications and smoother hardware integrations directly on your phone.",
        "news-date-schiessbuch": "June 2026",
        "news-heading-schiessbuch": "📋 Digital Shooting Log (12/18 proof)",
        "news-body-schiessbuch": "Keep your shooting log fully digital and tamper-resistant. Have your training sessions signed directly on the range and generate a verified PDF report for your authority with one click.",
        "news-date-sgtimer-live": "June 2026",
        "news-heading-sgtimer-live": "⏱️ SG-Timer Live Integration",
        "news-body-sgtimer-live": "Connect your Shooters Global Timer wirelessly via Bluetooth directly to the platform. Track your splits live, control your device remotely and send your times into global drill comparisons.",
        "news-date-reload": "June 2026",
        "news-heading-reload": "📦 New Section: Reloading Database",
        "news-body-reload": "The reloading corner is officially live! Save your proven loads, powder charges, and OAL values safely to your personal cloud database and access them anytime straight from the range.",
        "news-date-1": "June 2026",
        "news-heading-1": "📱 The IPSC Exchange as a real App (PWA)",
        "news-body-1": "We made the platform 'App-ready'! You can now easily install the site via your mobile browser (Safari/Chrome) using 'Add to Home Screen' as a full app on your smartphone – including a stylish IPSC target icon.",
        "news-date-2": "May 2026",
        "news-heading-2": "⏱️ New Section: Tools & Training integrated",
        "news-body-2": "From now on, powerful training helpers are available to you. Calculate your hit factor precisely directly on the range or use our responsive dry-fire timer for your dry training at home.",
        "news-date-3": "April 2026",
        "news-heading-3": "🛡️ 'Trusted Shooter' Reputation System",
        "news-body-3": "To maximize security on the marketplace, a reputation system was introduced. By storing your IPSC alias you receive a verified badge, and successful deals can be rated mutually.",
        "card-title-market": "Marketplace",
        "card-desc-market": "Search for available starting slots for fully booked matches or offer your own ticket for exchange.",
        "card-action-market": "To Marketplace &rarr;",
        "card-title-free": "Matches",
        "card-desc-free": "Live capacity tracker for MatchSign. Find tournaments instantly that currently still have free slots.",
        "card-action-free": "Check free slots &rarr;",
        "card-title-planer": "My Planner",
        "card-desc-planer": "Plan your perfect IPSC season, keep an eye on deadlines and export your matches directly to your calendar.",
        "card-action-planer": "Plan season &rarr;",
        "card-title-comm": "Community",
        "card-desc-comm": "Network with other shooters, discuss equipment and share posts in the social feed.",
        "card-action-comm": "To Community &rarr;",
        "card-title-hub": "IPSC Hub",
        "card-desc-hub": "No more searching: All important links to MatchSign, PractiScore, IPSCess, associations and rulebooks bundled.",
        "card-action-hub": "To Link Hub &rarr;",
        "card-title-tools": "Tools & Training",
        "card-desc-tools": "Interactive hit factor calculator, stage planning assistant and a configurable dry-fire timer for your training.",
        "card-action-tools": "To Tools &rarr;",

        // --- KONTO-EINSTELLUNGEN MODAL (ALLE SEITEN) ---
        "modal-settings-title": "Account Settings",
        "modal-settings-deals": "📈 Successful Mediations",
        "modal-settings-seller": "As Seller",
        "modal-settings-buyer": "As Buyer",
        "modal-settings-comm": "💬 Communication:",
        "modal-settings-pay": "💳 Payment:",
        "modal-settings-passkey-title": "🔒 Passkey (Quick Login)",
        "modal-settings-passkey-desc": "Link your current device to log in without a password via FaceID, fingerprint, or PIN in the future.",
        "modal-settings-passkey-btn": "Register device as Passkey",
        "lbl-username": "Shooter Name / Display Name",
        "lbl-ipsc-alias": "🛡️ IPSC Alias / Member Number",
        "lbl-ipsc-alias-desc": "If you fill in this field, you will receive the 'Trusted Shooter' badge on your listings!",
        "lbl-real-name": "🔒 Real Name (For automatic analytics)",
        "lbl-real-name-desc": "Enter your real name here (e.g., John Doe). This name will never be displayed publicly. It is only used by the night scraper to map your match hits.",
        "ph-real-name": "e.g. John Doe",
        "lbl-profile-pic": "Profile Picture (Optional)",
        "lbl-change-password": "New password (optional)",
        "btn-delete-acc": "Irrevocably delete account & all entries",
        
        // --- PLATZHALTER-ÜBERSETZUNGEN ---
        "ph-username": "e.g. IPSCShooter99",
        "ph-ipsc-alias": "e.g. GER1234 (Optional)",
        "ph-password": "At least 6 characters (Leave blank to keep current)",

        // --- MARKETPLACE STATIC ELEMENTS (marktplatz.html) ---
        "info-msg": "<strong>Important Notice:</strong> This platform is for mediation purposes only. The final reassignment of the starting slot must be processed by the respective Match Director!",
        "form-title": "Create Entry",
        "opt-offer": "I AM OFFERING a starting slot",
        "opt-want": "I AM LOOKING FOR a starting slot",
        "lbl-name": "Match Name *",
        "lbl-level": "Match Level *",
        "lbl-date": "Match Date *",
        "lbl-country": "Country *",
        "lbl-location": "Range Location *",
        "lbl-squad": "Squad Number (Optional)",
        "lbl-price": "Asking Price (€) *",
        "lbl-email": "Your Email Address *",
        "btn-cancel": "Cancel",
        "btn-insert": "Publish Entry for Free",
        "filter-type": "Listing Type:",
        "filter-all": "All Listings",
        "filter-offers": "Offers Only (Selling)",
        "filter-wants": "Requests Only (Buying)",
        "list-title": "Current Marketplace Entries",
        "loading": "Loading available slots...",

        "market-form-kicker": "Marketplace",
        "market-form-title": "Create listing",
        "market-form-text": "Offer or search for a match slot",
        "planner-form-kicker": "Season Planner",
        "planner-form-title": "Create match",
        "planner-form-text": "Add a new match to your season plan",
        "label-squad": "Squad",
        "listed-by": "Listed by",
        "trusted-badge": "Trusted",
        "trusted-title": "Verified IPSC alias",
        "btn-live-chat": "Live Chat",
        "btn-mediated": "Mediated",

        // --- MARKETPLACE ERWEITERTE POPUPS ---
        "mediated-title": "Slot Successfully Mediated",
        "mediated-desc": "Enter the buyer's email address here and rate the transaction to complete it. The successful mediation will be stored in your profile statistics.",
        "lbl-buyer-email": "Buyer's Email Address *",
        "lbl-rating-comm": "💬 Communication",
        "lbl-rating-pay": "💳 Payment",
        "btn-mediated-submit": "Confirm Mediation & Close Entry",

        // --- MARKETPLACE DYNAMIC JAVASCRIPT TEXTS (app.js) ---
        "no-slots": "No marketplace entries available.",
        "btn-request": "Contact Seller",
        "btn-contact-want": "Contact Shooter",
        "btn-delete": "Delete",
        "btn-edit": "Edit",
        "btn-manage": "Manage",
        "btn-export": "Export (.ics)",
        "report-btn": "Report",
        "form-title-edit": "Edit Entry ✏️",
        "btn-save-edit": "Save Changes",
        "login-required": "Only logged-in users can contact shooters.",
        "tag-offer": "OFFER",
        "tag-want": "WANTED",
        "spam-error": "Spam protection: You have already posted an entry for this match on this date!",
        "email-subject-offer": "Inquiry regarding your IPSC slot: ",
        "email-subject-want": "Regarding your request for an IPSC slot: ",
        "email-body-offer": "Hello,\n\nI saw your listing on ipscboerse.com and I am interested in the slot you offered for the match: ",
        "email-body-want": "Hello,\n\nI saw your request on ipscboerse.com. I have an available slot to give away for the match: ",
        "email-body-footer": "\n\nIs this listing still available?\n\nBest regards",
        "security-checklist": "\n\nSecurity checklist before email:\n- Match details verified?\n- Match Director contacted?",
        "security-notice": "⚠️ IMPORTANT SAFETY NOTICE:\n\n1. ALWAYS use PayPal with Buyer Protection for payments (never use 'Friends & Family').\n2. You MUST contact the Match Director BEFORE making any payment to confirm if a slot transfer is still permitted!\n\nDo you want to open the email client now?",

        // --- AVAILABLE MATCH SLOTS (freie-matches.html) ---
        "free-info-box": "<strong>Info:</strong> Matches are updated automatically in the background. Only tournaments with a capacity under 100% are displayed (free slots available).",
        "free-list-title": "Matches on MatchSign (Capacity < 100%)",
        "free-loading": "Loading current matches...",

        // --- COMPETITION PLANNER (mein-planer.html) ---
        "planner-logged-out-title": "Not Logged In",
        "planner-logged-out-desc": "Log in to make modifications to your matches and synchronize files with the cloud.",
        "planner-logged-out-btn": "Log In Now",
        "planner-title-my-matches": "My Matches",
        "planner-subtitle-new": "Add New Match",
        "planner-lbl-match-name": "Match Name",
        "planner-lbl-match-date": "Date",
        "planner-lbl-match-location": "Location / Country",
        "planner-btn-save": "Save Match to Cloud",
        "planner-subtitle-planned": "Planned Matches",
        "planner-loading": "Loading data from Supabase...",
        "planner-btn-export": "📅 Export to Calendar (.ics)",
        "planner-no-matches": "No matches added yet.",

        // --- COMMUNITY (community.html) ---
        "tab-posts": "Posts",
        "tab-groups": "Groups",
        "comm-logged-out-title": "Join the Community",
        "comm-logged-out-desc": "Please log in to read posts and discuss with other shooters.",
        "comm-logged-out-btn": "Log In Now",
        "comm-setup-title": "Choose your Alias",
        "comm-setup-desc": "Before starting in the community, please choose a shooter alias / display name (e.g., IPSCShooter99).",
        "comm-setup-btn": "Save Name & Start",
        "comm-loading": "Loading posts...",
        "fab-create-post": "Create Post",
        "comm-groups-coming": "Groups Feature (Coming Soon)",
        "comm-groups-desc": "Here you will soon be able to create private squad groups or club channels.",
        "modal-new-post": "New Post",
        "lbl-add-photo": "Add Photo (Optional)",
        "btn-share-post": "Share",

        // --- LOGIN & AUTH MODALS ---
        "modal-login-title": "Login",
        "link-forgot-pwd": "Forgot password?",
        "modal-btn-login": "Log in with Password",
        "modal-social-separator": "Or use quick login:",
        "modal-passkey-login": "With Face ID / Passkey",
        "modal-apple-login": "Sign in with Apple",
        "modal-google-login": "Sign in with Google",
        "lbl-password": "Password *",
        "modal-no-acc": "Don't have an account?",
        "modal-link-reg": "Register",
        "modal-reg-title": "Create Account",
        "modal-has-acc": "Already registered?",
        "modal-link-login": "To Login",
        "modal-forgot-title": "Forgot Password",
        "modal-btn-forgot": "Send Reset Link",
        "modal-reset-title": "Assign New Password",
        "lbl-new-password": "New Password *",

        // --- TOOLS (tools.html) ---
        "tools-hf-title": "🏆 Hit-Factor Battle",
        "tools-hf-desc": "Enter the results of you and your friends to create a live leaderboard for the stage.",
        "tools-hf-name": "Shooter Name",
        "tools-hf-pf": "Power Factor",
        "tools-hf-time": "Time (Sec.)",
        "tools-hf-scoring": "Scoring / Hits",
        "tools-hf-alpha": "Alpha (A)",
        "tools-hf-charlie": "Charlie (C)",
        "tools-hf-delta": "Delta (D)",
        "tools-hf-miss": "Miss (M)",
        "tools-hf-ns": "No-Shoot",
        "tools-hf-proc": "Procedure",
        "tools-hf-btn-submit": "Enter Shooter & Calculate",
        "tools-th-name": "Name",
        "tools-th-pts": "Pts",
        "tools-th-time": "Time",
        "tools-th-hf": "HF",
        "tools-hf-btn-clear": "Clear Leaderboard",
        "tools-df-title": "⏱️ Dry-Fire Timer & Drill Generator",
        "tools-df-placeholder": "Click the button to generate a random dry fire training drill.",
        "tools-df-btn-gen": "🎲 Generate New Drill",
        "tools-df-par": "Par Time (Seconds)",
        "tools-df-status-ready": "Ready",
        "tools-df-btn-start": "Start Timer (Random Delay)",
        "tools-pf-title": "⏱️ IPSC Power-Factor Manager",
        "tools-pf-desc": "Calculate the power factor of your load and check the match status.",
        "tools-pf-weight": "Bullet Weight (Grains)",
        "tools-pf-velocity": "Velocity (fps)",
        "tools-pf-target": "Target Scoring",
        "tools-pf-opt-minor": "Minor (Minimum Factor 125)",
        "tools-pf-opt-major": "Major (Minimum Factor 160)",
        "tools-pf-result-label": "Calculated Power Factor",
        "tools-db-title": "📦 My Reloading Recipes",
        "tools-db-desc": "Save your proven loads permanently to your secure cloud database.",
        "tools-db-logged-out": "Log in to access your personal reloading recipe database and synchronize files with the cloud.",
        "tools-db-caliber": "Caliber",
        "tools-db-bullet-type": "Bullet Type / Maker",
        "tools-db-bullet-type-ph": "e.g. LOS HP or H&N HS",
        "tools-db-powder": "Powder (Type & Amount)",
        "tools-db-powder-ph": "e.g. 3.7gr N320",
        "tools-db-oal": "OAL (mm)",
        "tools-db-oal-ph": "e.g. 29.00",
        "tools-db-notes": "Notes / Gun (Optional)",
        "tools-db-notes-ph": "e.g. Safe minor factor out of CZ Shadow 2",
        "tools-db-btn-save": "💾 Save Recipe to Cloud",
        "tools-db-saved-title": "Load data",

        // --- IPSC HUB ---
        "hub-main-title": "IPSC Hub – All Important Links",
        "hub-main-desc": "No more endless searching: All important links to MatchSign, PractiScore, IPSCess, associations and rulebooks bundled.",
        "hub-cat-management": "🎯 Match Registrations & Management",
        "hub-desc-matchsign": "The most well-known and used platform for IPSC match registrations in Germany.",
        "hub-btn-matchsign": "Go to MatchSign",
        "hub-desc-ipscess": "Official portal for managing licenses, match points, and the IPSC ID card.",
        "hub-btn-ipscess": "Go to IPSCess Portal",
        "hub-desc-practiscore": "The international system. Essential for foreign matches and live scoring on-site.",
        "hub-btn-practiscore": "Go to PractiScore",
        "hub-desc-makeready": "Frequently used for large international tournaments and matches in neighboring European countries.",
        "hub-btn-makeready": "Go to MakeReady",
        "hub-cat-stats": "📊 Statistics & Rankings",
        "hub-desc-ipscelo": "Unofficial but fantastic Elo ranking and statistics tool based on international match results.",
        "hub-btn-ipscelo": "Go to IPSCelo",
        "hub-cat-rules": "📖 Associations & Rulebooks",
        "hub-desc-bds": "The Federation of German Sport Shooters. Official contact point for sports regulations, endorsements, and dates.",
        "hub-btn-bds": "Go to BDS",
        "hub-desc-rules": "The current international rulebooks (Handgun, Rifle, PCC, Shotgun) directly as PDF for download.",
        "hub-btn-rules": "Go to Rulebooks",

        // --- PERFORMANCE ANALYTICS & DASHBOARD ---
        "analytics-title": "🏆 IPSC Performance Analytics",
        "analytics-desc": "Track your athletic progress, shooting precision, and hit factor trends across your matches.",
        "analytics-kpi-matches": "Total Matches",
        "analytics-kpi-avg-hf": "Avg Hit Factor",
        "analytics-chart-title": "📈 Hit Factor Trend (Last 5 Stages)",
        "analytics-acc-title": "🎯 Hit Distribution (Accuracy)",
        "analytics-box-title": "📧 Enter A, C, D automatically",
        "analytics-box-desc": "Results and hit factor are loaded automatically. If you also want <strong>A, C, D and Misses</strong> entered automatically, simply forward your PractiScore emails to <strong style='color: var(--text-color);'>info@ipscboerse.com</strong> after the match!",

        // --- IMPRESSUM & RECHTLICHES (EN) ---
        "imp-back": "← Back to home",
        "imp-h2-1": "1. Legal Notice (Impressum)",
        "imp-p-1": "<strong>Information pursuant to § 5 TMG:</strong><br>Fabian Schöps<br>Weserblick 9<br>34399 Wesertal, Germany",
        "imp-p-contact": "<strong>Contact:</strong><br>Email: <a href='mailto:info@ipscboerse.com'>info@ipscboerse.com</a>",
        "imp-h2-2": "2. Terms and Conditions (T&C) & Terms of Use",
        "imp-h3-1": "§ 1 Scope and Purpose of the Platform",
        "imp-p-2": "The platform (ipscboerse.com) provides exclusively a technical infrastructure ('bulletin board') to connect sports shooters with each other for the transfer of match slots. The operator of this website does <strong>not</strong> act as an organizer, buyer, seller, or official intermediary of starting slots. Contracts for slot exchanges are made exclusively between the participating users.",
        "imp-h3-2": "§ 3 User Obligations & Code of Conduct",
        "imp-p-3": "Users agree to use the platform exclusively for its intended legal purpose. It is strictly prohibited to publish content (posts, chat messages, comments, or images) that:",
        "imp-li-1": "Contains insults, defamation, threats, hate speech, racism, or discrimination.",
        "imp-li-2": "Displays pornographic, sexually explicit (including commercial swimwear/underwear), or youth-endangering imagery.",
        "imp-li-3": "Depicts violence-glorifying, extremist, or unconstitutional material.",
        "imp-li-4": "Violates applicable law (e.g., copyright law, criminal law) or pursues spam or fraudulent intentions.",
        "imp-li-5": "Serves commercial or profit-oriented ticket resale (reselling/scalping). Starting slots may be offered at a maximum of the organizer's official original price.",
        "imp-h3-3": "§ 3 Automated Moderation & Virtual House Rules",
        "imp-p-4": "To ensure the safety, youth protection, and quality of the marketplace, the operator uses automated filters and AI systems for real-time moderation:",
        "imp-li-6": "<strong>Text Filter:</strong> All submitted posts and comments are fully automatically checked against an integrated list of impermissible terms and profanity.",
        "imp-li-7": "<strong>Image AI:</strong> Uploaded image files are scanned via software using artificial intelligence for visual guideline violations (such as nudity or partial nudity).",
        "imp-p-5": "If a post or comment violates these guidelines, the entry will be <span class='highlight'>immediately, fully automatically, and irrevocably deleted without prior warning</span>. The operator reserves the right under its virtual house rules to temporarily or permanently suspend user accounts in the event of violations.",
        "imp-h3-4": "§ 4 Disclaimer of Liability",
        "imp-p-6": "We explicitly assume no liability for:",
        "imp-li-8": "The actual completion of starting slot transfers.",
        "imp-li-9": "The accuracy of match data, deadlines, or prices posted by users in chats or listings.",
        "imp-li-10": "Financial losses or damages caused by fraud or discrepancies between users.",
        "imp-li-11": "The final decision of the respective Match Director (organizer) regarding whether a transfer is accepted.",
        "imp-alert-title": "IMPORTANT NOTICE REGARDING TRANSACTIONS:",
        "imp-alert-desc": "The financial transaction and the final transfer with the Match Director are 100% the responsibility of the respective users. We strongly advise completing payments exclusively via secure methods (e.g., PayPal with buyer protection) and obtaining the organizer's explicit consent BEFORE making a payment.",
        "imp-h2-3": "3. Privacy Policy",
        "imp-p-7": "We take the protection of your personal data very seriously. This privacy policy informs you about the type, scope, and purpose of processing personal data on our platform.",
        "imp-h3-5": "1. Data Controller",
        "imp-p-8": "The controller responsible for data processing is the website operator named in the Legal Notice above.",
        "imp-h3-6": "2. Collection and Processing of User Data",
        "imp-p-9": "To create listings, use the live chat, or contact sellers, you must create a user account. During this process, we collect the following data:",
        "imp-li-12": "<strong>Email Address:</strong> Necessary for login, verification, system notifications, chat message assignment, and contact purposes.",
        "imp-li-13": "<strong>Password:</strong> Stored cryptographically encrypted (no plaintext access for the operator).",
        "imp-li-14": "<strong>Username (Optional):</strong> For display on the platform within your posts.",
        "imp-li-15": "<strong>Chat Messages:</strong> Message histories exchanged within the integrated live chat are stored in the database to provide the chat function.",
        "imp-li-16": "<strong>User-generated Content:</strong> Posted match data, descriptions, prices, comments, and uploaded images.",
        "imp-h3-7": "3. Visibility of Your Data & Live Chat Functionality",
        "imp-p-10": "The core principle of this exchange is the transfer of starting slots. <strong>When you create a listing or use the live chat, the relevant data is visible to the respective chat partners.</strong> Within marketplace listings, your email address is accessible to other logged-in users to enable contact (Art. 6 (1) lit. a and lit. b GDPR).",
        "imp-p-11": "Additionally, a manual function is available in the live chat allowing users to 'nudge' their chat partner via email. This opens the user's local email program via a mailto-link independently; no automated data forwarding to third-party providers takes place in the background via this interface.",
        "imp-h3-8": "4. Automated Content Verification & Data Transmission",
        "imp-p-12": "To protect our legitimate interest in a secure, legally compliant, and disruption-free platform (Art. 6 (1) lit. f GDPR), content is processed as follows:",
        "imp-li-17": "<strong>Image Scans (Sightengine):</strong> When an image is uploaded, its URL is automatically transmitted to the API of the inspection service Sightengine (Sightengine SAS, France/EU). The image is purely machine-analyzed for violations (e.g., nudity filters). No permanent storage or use of the images for third-party purposes or AI training by the service provider occurs.",
        "imp-h3-9": "5. Use of Supabase (Hosting, Data Storage & Live Chat)",
        "imp-p-13": "This website uses the backend service 'Supabase' (Supabase Inc., San Francisco, USA) for the central database, storing chat histories (Live Chat), file storage, and user authentication. Your data is hosted and processed on infrastructures provided by Supabase within the EU (Region: Frankfurt am Main, Germany). We have concluded a legally binding Data Processing Addendum (DPA) with the provider pursuant to Art. 28 GDPR. Further info: <a href='https://supabase.com/privacy' target='_blank' rel='noopener'>Supabase Privacy</a>.",
        "imp-h3-10": "6. Match Analytics & Results Scraper",
        "imp-p-14": "If you enter your real name in your profile settings on our platform, we use automated systems at your explicit request to search publicly accessible internet IPSC tournament result lists for this name. The hits concerning you (such as match name, stage, hit factors) are imported into our database to display your statistics (Art. 6 (1) lit. b GDPR). <strong>Important:</strong> Data of third persons who are also on these lists are only processed fleetingly in the memory of our systems and immediately discarded. No storage or profiling of foreign personal data takes place.",
        "imp-h3-11": "7. Cookies & Local Storage",
        "imp-p-15": "To maintain your login status across browser sessions, Supabase stores an authentication token in the 'Local Storage' of your device. This is a technically strictly necessary process (Art. 6 (1) lit. f GDPR). No marketing, tracking, or advertising cookies are used.",
        "imp-h3-12": "8. Deletion of Data upon Request",
        "imp-p-16": "You can immediately, permanently, and irrevocably remove your entire profile, all your listings, written comments, and your complete personal chat histories from our live database with one click on 'Irrevocably delete account & all entries' in your account settings.",
        "imp-h3-13": "9. Your Rights",
        "imp-p-17": "Under the GDPR, you have the right to free information about your stored data, correction, blocking, or deletion of this data, as well as the right to data portability. Please contact the email address provided in the Legal Notice at any time for this purpose."
    }
};

// Automatischer Übersetzungs-Ablauf für statische Elemente und Input-Platzhalter
window.translatePortalPage = function() {
    const lang = localStorage.getItem("selectedLanguage") || "de";
    window.currentLang = lang;
    
    // 1. Standard-Labels übersetzen
    document.querySelectorAll("[data-txt]").forEach(el => {
        const key = el.getAttribute("data-txt");
        if (window.portalTranslations[lang] && window.portalTranslations[lang][key]) {
            el.innerHTML = window.portalTranslations[lang][key];
        }
    });

    // 2. Input-Platzhalter übersetzen
    document.querySelectorAll("[data-txt-ph]").forEach(el => {
        const key = el.getAttribute("data-txt-ph");
        if (window.portalTranslations[lang] && window.portalTranslations[lang][key]) {
            el.placeholder = window.portalTranslations[lang][key];
        }
    });
    
    if (typeof window.onLanguageChanged === "function") {
        window.onLanguageChanged();
    }
};

window.translations = window.portalTranslations;

document.addEventListener("change", (e) => {
    if (e.target && e.target.id === "language-select") {
        localStorage.setItem("selectedLanguage", e.target.value);
        window.translatePortalPage();
        try { window.dispatchEvent(new CustomEvent("ipsc:language-change-v78d", { detail: { lang: e.target.value } })); } catch (_) {}
    }
});

if (document.readyState === 'loading') {
    document.addEventListener('DOMContentLoaded', window.translatePortalPage);
} else {
    window.translatePortalPage();
}


// --- V74 Native Logic Polish translations ---
(function() {
    window.portalTranslations = window.portalTranslations || {};
    window.portalTranslations.de = Object.assign(window.portalTranslations.de || {}, {
    "v74-home-kicker": "IPSC Startplatz-Börse",
    "v74-home-title": "Deine IPSC-Zentrale.",
    "v74-home-desc": "Startplätze finden, Matches planen, Schießbuch führen und Training auswerten — alles an einem Ort, schnell erreichbar und gemacht für den Alltag auf dem Stand.",
    "v74-home-action-market": "Startplatz finden",
    "v74-home-action-planner": "Saison planen",
    "v74-home-quick-market": "Startplatz finden",
    "v74-home-quick-market-desc": "Angebote & Gesuche öffnen",
    "v74-home-quick-log": "Schießbuch öffnen",
    "v74-home-quick-log-desc": "Einträge, PDF & QR",
    "v74-home-quick-tools": "Training auswerten",
    "v74-home-quick-tools-desc": "Hit-Factor & Tools",
    "v74-market-kicker": "Startplatz-Börse",
    "v74-market-title": "Marktplatz",
    "v74-market-desc": "Startplätze anbieten, suchen und sauber organisieren — mit klaren Anzeigen, Status und direktem Kontakt.",
    "v74-market-action-create": "Anzeige erstellen",
    "v74-market-action-free": "Freie Startplätze",
    "v74-market-status": "Vermittlung, Kontakt und Übersicht — die offizielle Umschreibung erfolgt weiterhin über den Match Director.",
    "v74-planner-kicker": "Saisonplanung",
    "v74-planner-title": "Mein Planer",
    "v74-planner-desc": "Matches, Adressen und Notizen für deine Saison — übersichtlich, privat und schnell erreichbar.",
    "v74-planner-action-add": "Match hinzufügen",
    "v74-planner-action-list": "Geplante Matches",
    "v74-planner-status": "Plane deine Saison, öffne Routen in Apple/Google Maps und halte private Notizen fest.",
    "v74-community-kicker": "IPSC Community",
    "v74-community-title": "Community",
    "v74-community-desc": "Fragen stellen, Trainingsideen teilen, Match-Erfahrungen sammeln und mit anderen Schützen in Kontakt bleiben.",
    "v74-community-action-post": "Beitrag schreiben",
    "v74-community-action-feed": "Beiträge ansehen",
    "v74-community-status": "Moderierter Austausch für Fragen, Training, Matchberichte, Ausrüstung und Vereine.",
    "v74-free-kicker": "Freie Startplätze",
    "v74-free-title": "Matches",
    "v74-free-desc": "Finde freie Startplätze schneller und filtere verfügbare Matches nach Land, Disziplin und Level.",
    "v74-free-action-show": "Freie Startplätze anzeigen",
    "v74-free-action-market": "Zum Marktplatz",
    "v74-free-status": "Quelle: MatchSign · angezeigt werden Matches mit freien Startplätzen.",
    "v74-log-kicker": "Digitales Schießbuch",
    "v74-log-title": "Schießbuch",
    "v74-log-desc": "Training dokumentieren, Einträge bestätigen lassen, PDF exportieren und Integrität per Hash/QR nachvollziehbar halten.",
    "v74-log-action-add": "Eintrag hinzufügen",
    "v74-log-action-pdf": "PDF exportieren",
    "v74-log-status": "Hash-Prüfung, QR-Verifikation und externer Bestätigungsfluss für deine Dokumentation.",
    "v74-tools-kicker": "Training Tools",
    "v74-tools-title": "Tools",
    "v74-tools-desc": "Hit-Factor Battle, Stage-Auswertung und praktische Helfer für Training, Squad-Vergleich und Match-Vorbereitung.",
    "v74-tools-action-hf": "Hit-Factor Battle",
    "v74-tools-action-log": "Schießbuch öffnen",
    "v74-tools-status": "Rechner, Auswertung und Exportfunktionen für Training und Wettkampfvorbereitung.",
    "v74-perf-kicker": "Performance Check",
    "v74-perf-title": "Performance",
    "v74-perf-desc": "Starterlisten analysieren, Konkurrenz einschätzen und dein Match realistischer vorbereiten.",
    "v74-perf-action-start": "Analyse starten",
    "v74-perf-action-analytics": "Statistiken öffnen",
    "v74-perf-status": "Starterlisten, Divisionsvergleich und Performance-Einschätzung in einem Bereich.",
    "v74-analytics-kicker": "Statistiken",
    "v74-analytics-title": "Statistiken",
    "v74-analytics-desc": "Startplätze, Muster und Chancen besser verstehen — als persönlicher Überblick für ambitionierte Schützen.",
    "v74-analytics-action-radar": "Buddy-Radar öffnen",
    "v74-analytics-action-perf": "Performance Check",
    "v74-analytics-status": "Persönliche Auswertung, Startplatzmuster und Match-Übersichten.",
    "v74-hub-kicker": "IPSC Hub",
    "v74-hub-title": "IPSC Hub",
    "v74-hub-desc": "Der schnelle Einstieg in die wichtigsten Bereiche, Tools und Informationen deiner IPSC-Börse.",
    "v74-hub-action-tools": "Tools öffnen",
    "v74-hub-action-planner": "Planer öffnen",
    "v74-hub-status": "Zentrale Navigation für Marktplatz, Training, Planung und Dokumentation.",
    "v74-reload-kicker": "Wiederladen",
    "v74-reload-title": "Wiederladen",
    "v74-reload-desc": "Daten, Notizen und Helfer rund um Laborierungen strukturiert und schnell erreichbar.",
    "v74-reload-action-calc": "Power-Factor prüfen",
    "v74-reload-action-tools": "Tools öffnen",
    "v74-reload-status": "Laborierungsnotizen, Power-Factor und praktische Hilfen für den Stand.",
    "v74-aa-kicker": "Doppel-AA",
    "v74-aa-title": "Doppel-AA",
    "v74-aa-desc": "Trainings- und Leistungsbereich mit klarer Struktur für fokussierte Vorbereitung.",
    "v74-aa-action-start": "Bereich öffnen",
    "v74-aa-action-performance": "Performance Check",
    "v74-aa-status": "Fokusbereich für Training, Analyse und persönliche Entwicklung.",
    "v74-timer-kicker": "Live Timer",
    "v74-timer-title": "SG Timer Live",
    "v74-timer-desc": "Timer- und Trainingsfunktionen mit schneller Bedienung und app-typischem Fokus.",
    "v74-timer-action-open": "Timer öffnen",
    "v74-timer-action-tools": "Tools öffnen",
    "v74-timer-status": "Live-Training, Timer-Daten und schnelle Auswertung für den Stand.",
    "v74-community-composer-title": "Was möchtest du teilen?",
    "v74-community-composer-subtitle": "Frage, Training, Matchbericht oder Tipp posten",
    "v74-community-composer-button": "Posten",
    "v74-community-filter-all": "Alle",
    "v74-community-filter-question": "Frage",
    "v74-community-filter-training": "Training",
    "v74-community-filter-match": "Matchbericht",
    "v74-community-filter-equipment": "Ausrüstung",
    "v74-community-filter-club": "Verein",
    "v74-community-category-admin": "Admin-Update",
    "v74-community-category-label": "Kategorie",
    "v74-community-post-placeholder": "Was gibt's Neues rund um IPSC?"
});
    window.portalTranslations.en = Object.assign(window.portalTranslations.en || {}, {
    "v74-home-kicker": "IPSC Slot Exchange",
    "v74-home-title": "Your IPSC command center.",
    "v74-home-desc": "Find match slots, plan your season, keep your shooting log and analyze training — all in one place, fast and built for the range.",
    "v74-home-action-market": "Find a slot",
    "v74-home-action-planner": "Plan season",
    "v74-home-quick-market": "Find a slot",
    "v74-home-quick-market-desc": "Open offers & requests",
    "v74-home-quick-log": "Open logbook",
    "v74-home-quick-log-desc": "Entries, PDF & QR",
    "v74-home-quick-tools": "Analyze training",
    "v74-home-quick-tools-desc": "Hit factor & tools",
    "v74-market-kicker": "Slot Exchange",
    "v74-market-title": "Marketplace",
    "v74-market-desc": "Offer, request and organize IPSC match slots with clear listings, status and direct contact.",
    "v74-market-action-create": "Create listing",
    "v74-market-action-free": "Open slots",
    "v74-market-status": "Exchange, contact and overview — official slot transfers still happen through the match director.",
    "v74-planner-kicker": "Season Planning",
    "v74-planner-title": "My Planner",
    "v74-planner-desc": "Matches, addresses and notes for your season — clear, private and easy to reach.",
    "v74-planner-action-add": "Add match",
    "v74-planner-action-list": "Planned matches",
    "v74-planner-status": "Plan your season, open routes in Apple/Google Maps and keep private notes.",
    "v74-community-kicker": "IPSC Community",
    "v74-community-title": "Community",
    "v74-community-desc": "Ask questions, share training ideas, collect match experience and stay connected with other shooters.",
    "v74-community-action-post": "Write post",
    "v74-community-action-feed": "View posts",
    "v74-community-status": "Moderated exchange for questions, training, match reports, equipment and clubs.",
    "v74-free-kicker": "Open Slots",
    "v74-free-title": "Open Matches",
    "v74-free-desc": "Find open match slots faster and filter available matches by country, discipline and level.",
    "v74-free-action-show": "Show open slots",
    "v74-free-action-market": "Marketplace",
    "v74-free-status": "Source: MatchSign · showing matches with open slots.",
    "v74-log-kicker": "Digital Logbook",
    "v74-log-title": "Shooting Log",
    "v74-log-desc": "Document training, request confirmations, export PDF and verify integrity with hash/QR checks.",
    "v74-log-action-add": "Add entry",
    "v74-log-action-pdf": "Export PDF",
    "v74-log-status": "Hash checks, QR verification and external confirmation flow for your documentation.",
    "v74-tools-kicker": "Training Tools",
    "v74-tools-title": "Tools",
    "v74-tools-desc": "Hit Factor Battle, stage scoring and practical helpers for training, squad comparison and match prep.",
    "v74-tools-action-hf": "Hit Factor Battle",
    "v74-tools-action-log": "Open logbook",
    "v74-tools-status": "Calculators, scoring and exports for training and match preparation.",
    "v74-perf-kicker": "Performance Check",
    "v74-perf-title": "Performance",
    "v74-perf-desc": "Analyze start lists, understand competition and prepare your match more realistically.",
    "v74-perf-action-start": "Start analysis",
    "v74-perf-action-analytics": "Open statistics",
    "v74-perf-status": "Start lists, division comparison and performance insights in one place.",
    "v74-analytics-kicker": "Statistics",
    "v74-analytics-title": "Statistics",
    "v74-analytics-desc": "Understand slots, patterns and opportunities — a personal overview for ambitious shooters.",
    "v74-analytics-action-radar": "Open buddy radar",
    "v74-analytics-action-perf": "Performance check",
    "v74-analytics-status": "Personal insights, slot patterns and match overviews.",
    "v74-hub-kicker": "IPSC Hub",
    "v74-hub-title": "IPSC Hub",
    "v74-hub-desc": "Fast access to the most important areas, tools and information in your IPSC exchange.",
    "v74-hub-action-tools": "Open tools",
    "v74-hub-action-planner": "Open planner",
    "v74-hub-status": "Central navigation for marketplace, training, planning and documentation.",
    "v74-reload-kicker": "Reloading",
    "v74-reload-title": "Reloading",
    "v74-reload-desc": "Structured data, notes and helpers around loads and ammunition preparation.",
    "v74-reload-action-calc": "Check power factor",
    "v74-reload-action-tools": "Open tools",
    "v74-reload-status": "Load notes, power factor and practical helpers for the range.",
    "v74-aa-kicker": "Double-AA",
    "v74-aa-title": "Double-AA",
    "v74-aa-desc": "Training and performance area with clear structure for focused preparation.",
    "v74-aa-action-start": "Open area",
    "v74-aa-action-performance": "Performance check",
    "v74-aa-status": "Focus area for training, analysis and personal development.",
    "v74-timer-kicker": "Live Timer",
    "v74-timer-title": "SG Timer Live",
    "v74-timer-desc": "Timer and training functions with fast operation and app-like focus.",
    "v74-timer-action-open": "Open timer",
    "v74-timer-action-tools": "Open tools",
    "v74-timer-status": "Live training, timer data and fast evaluation for the range.",
    "v74-community-composer-title": "What would you like to share?",
    "v74-community-composer-subtitle": "Post a question, training idea, match report or tip",
    "v74-community-composer-button": "Post",
    "v74-community-filter-all": "All",
    "v74-community-filter-question": "Question",
    "v74-community-filter-training": "Training",
    "v74-community-filter-match": "Match report",
    "v74-community-filter-equipment": "Equipment",
    "v74-community-filter-club": "Club",
    "v74-community-category-admin": "Admin update",
    "v74-community-category-label": "Category",
    "v74-community-post-placeholder": "What's new around IPSC?"
});
})();


// --- V75 Final UI Cleanup translations ---
(function() {
    window.portalTranslations = window.portalTranslations || {};
    window.portalTranslations.de = Object.assign(window.portalTranslations.de || {}, {
    "btn-logout": "Abmelden",
    "v75-planner-status": "Bei exakter Match-Namenseingabe kann das System passende Matchdaten automatisch erkennen und deine Planung schneller vorbereiten.",
    "v75-free-status": "Die Liste wird automatisch synchronisiert. Angezeigt werden verfügbare Matches mit freien Startplätzen.",
    "v75-market-status": "Anzeige erstellen, Kontakt aufnehmen und Status behalten — die offizielle Umschreibung läuft weiterhin über den Match Director.",
    "v75-community-status": "Wähle eine Kategorie, poste deine Frage oder deinen Matchbericht und filtere den Feed nach Themen.",
    "v75-tools-status": "Stage-Auswertung und Hit-Factor-Tools laufen direkt auf dieser Seite — ohne zusätzliche Navigation im Hero.",
    "v75-analytics-status": "Automatische Auswertungen laufen im Hintergrund, wenn passende Daten vorhanden sind.",
    "v75-performance-status": "Vereinsbereich: Starterlisten und Planner-Daten werden automatisch mit deiner Performance verglichen.",
    "v75-aa-status": "Vereinsbereich: offene Anmeldungen und Bot-Status werden automatisch abgeglichen.",
    "v75-hub-status": "Alle wichtigen Links und Plattformen sind direkt unten auf dieser Seite gebündelt.",
    "v75-reload-status": "Power-Factor und Laborierungswerte werden direkt unten auf dieser Seite berechnet.",
    "v75-timer-status": "Live-Konsole und Bestenlisten liegen direkt darunter — schnell erreichbar ohne zusätzliche Hero-Buttons.",
    "v75-log-status": "Einträge, PDF-Export, QR-Prüfung und externe Bestätigung liegen direkt unten im Schießbuch.",
    "v75-community-empty-title": "Noch keine Beiträge",
    "v75-community-empty-desc": "Starte die erste Diskussion, teile einen Trainingstipp oder stelle eine Frage an die Community.",
    "v75-community-load-error": "Fehler beim Laden.",
    "v75-community-check-image": "Prüfe Bild auf zulässige Inhalte...",
    "v75-community-uploading": "Wird hochgeladen..."
});
    window.portalTranslations.en = Object.assign(window.portalTranslations.en || {}, {
    "btn-logout": "Logout",
    "v75-planner-status": "Enter the exact match name and the system can automatically detect matching match data to speed up your planning.",
    "v75-free-status": "The list synchronizes automatically. Only matches with open slots are shown.",
    "v75-market-status": "Create listings, contact shooters and keep track — official transfers still happen through the match director.",
    "v75-community-status": "Choose a category, post your question or match report and filter the feed by topic.",
    "v75-tools-status": "Stage scoring and hit factor tools are directly on this page — no extra hero navigation needed.",
    "v75-analytics-status": "Automatic insights run in the background when matching data is available.",
    "v75-performance-status": "Club area: start lists and planner data are automatically compared with your performance.",
    "v75-aa-status": "Club area: open registrations and bot status are automatically synchronized.",
    "v75-hub-status": "All important links and platforms are bundled directly below on this page.",
    "v75-reload-status": "Power factor and load values are calculated directly below on this page.",
    "v75-timer-status": "Live console and leaderboards are directly below — fast access without extra hero buttons.",
    "v75-log-status": "Entries, PDF export, QR verification and external confirmation are directly below in the logbook.",
    "v75-community-empty-title": "No posts yet",
    "v75-community-empty-desc": "Start the first discussion, share a training tip or ask the community a question.",
    "v75-community-load-error": "Could not load posts.",
    "v75-community-check-image": "Checking image for allowed content...",
    "v75-community-uploading": "Uploading..."
});
})();


// --- V76 Full Cleanup translations ---
(function() {
    window.portalTranslations = window.portalTranslations || {};
    window.portalTranslations.de = Object.assign(window.portalTranslations.de || {}, {
    "v76-market-desc": "Finde Startplätze für ausgebuchte Matches oder biete deinen Platz an, wenn du selbst nicht teilnehmen kannst.",
    "v76-market-status": "",
    "v76-planner-desc": "Behalte deine Matches im Blick: Anmeldungen, Wartelistenplätze und bestätigte Squads werden übersichtlich zusammengeführt.",
    "v76-planner-status": "Tipp: Hinterlege in deinem Profil deinen Namen so, wie er in den Starterlisten erscheint. So kann die App öffentlich verfügbare Matchdaten von IPSCmatch.de besser zuordnen. Matches von anderen Plattformen kannst du jederzeit manuell hinzufügen.",
    "v76-planner-manual-title": "Match manuell hinzufügen",
    "v76-planner-manual-desc": "Wenn ein Match nicht automatisch erkannt wird",
    "v76-planner-legend-approved": "im Squad bestätigt",
    "v76-planner-legend-waitlist-label": "Warteliste",
    "v76-planner-legend-waitlist": "noch nicht eingebucht",
    "v76-community-desc": "Stelle Fragen, teile Trainingstipps und bleib mit anderen IPSC-Schützen im Austausch.",
    "v76-community-status": "",
    "v76-free-desc": "Sieh auf einen Blick, welche Matches noch freie Startplätze haben, ohne jede Ausschreibung einzeln öffnen zu müssen.",
    "v76-free-status": "Die Übersicht wird automatisch aktualisiert und zeigt nur Matches, bei denen laut MatchSign noch freie Plätze verfügbar sind.",
    "v76-free-list-title": "Verfügbare Matches",
    "v76-free-source": "Quelle: MatchSign · Auslastung unter 100 %",
    "v76-log-desc": "Training dokumentieren, Einträge bestätigen lassen, PDF exportieren und Integrität per Hash/QR nachvollziehbar halten.",
    "v76-log-status": "Manipulationsschutz aktiv: Neue Einträge werden per Hash-Fingerabdruck gesichert und beim Signieren mit dem vorherigen Eintrag verkettet. Nach der Bestätigung wird der Eintrag gesperrt.",
    "v76-tools-desc": "Werte Stages aus, vergleiche Ergebnisse mit Freunden, speichere häufig genutzte Namen und exportiere deine Hit-Factor-Battles als PDF.",
    "v76-tools-status": "Gespeicherte Namen, mehrere Stages und PDF-Export helfen dir, Trainingsgruppen und kleine Battles schnell auszuwerten.",
    "v76-tools-hf-desc": "Erfasse Schützen, Zeiten, Treffer und Stages. Die App berechnet automatisch Hit-Factor, Platzierung und Gesamtwertung.",
    "v76-tools-dry-desc": "Generiere Dry-Fire-Drills und trainiere mit PAR-Zeit, Zufalls-Delay und klarer Timer-Anzeige.",
    "v76-tools-dry-start": "Start Timer (Zufalls-Delay)",
    "v76-analytics-desc": "Werte vergangene Matches aus, vergleiche Ergebnisse und behalte deine Entwicklung im Blick.",
    "v76-analytics-status": "Ergebnisse und Hit-Factor werden automatisch geladen. Für A-, C-, D-Treffer und Misses kannst du deine PractiScore-Mails nach dem Match an info@ipscboerse.com weiterleiten.",
    "v76-reload-desc": "Speichere deine Laborierungen, prüfe den Power-Factor und behalte bewährte Rezepte für Training und Match im Blick.",
    "v76-reload-status": "Berechne den Power-Factor wahlweise mit FPS oder Meter pro Sekunde. Deine Laborierungen kannst du anschließend als Rezept speichern.",
    "v76-reload-unit-label": "Einheit",
    "v76-reload-recipes-desc": "Speichere bewährte Laborierungen mit Geschoss, Pulver, Geschwindigkeit, OAL und Notizen als persönliches Rezept.",
    "v76-reload-new-entry": "Neue Laborierung",
    "v76-reload-safety": "Hinweis: Prüfe Laborierungen immer eigenverantwortlich anhand offizieller Ladedaten und deiner eigenen Messwerte.",
    "v76-hub-desc": "Alle wichtigen Plattformen, Links und Informationen rund um IPSC zentral an einem Ort — von Match-Anmeldung über Ergebnisse bis zu Verbandsinfos.",
    "v76-hub-status": "",
    "v76-elo-kicker": "ELO-Vergleich",
    "v76-elo-title": "ELO-Vergleich",
    "v76-elo-desc": "Vergleiche deine ELO-Stärke mit dem Starterfeld kommender Matches und schätze dein Match schon vor dem ersten Schuss realistischer ein.",
    "v76-elo-status": "Wenn dein korrekter Name im Profil hinterlegt ist, erkennt die App passende kommende Matches automatisch. Du kannst ein Match mit einem Klick bestätigen oder alternativ einen IPSCMatch-Link mit Division einfügen.",
    "v76-elo-upcoming-title": "🎯 Automatisch erkannte kommende Matches",
    "v76-elo-welcome-title": "ELO-Vergleich",
    "v76-elo-welcome-desc": "Wähle ein automatisch erkanntes Match aus oder füge einen IPSCMatch-Link mit Division ein, um das Starterfeld mit deiner ELO-Stärke zu vergleichen.",
    "v76-bot-kicker": "Vereinsbereich",
    "v76-bot-title": "Startplatz-Bot",
    "v76-bot-desc": "Wähle kommende Matches aus und lasse dich automatisch anmelden, sobald die Anmeldung geöffnet wird.",
    "v76-bot-status": "Nur für Vereinsmitglieder: Der Bot überwacht ausgewählte Matches und versucht die Anmeldung automatisch, sobald sie möglich ist.",
    "v76-bot-info": "Hier siehst du kommende Matches, für die eine Anmeldung vorbereitet werden kann. Wähle ein Match aus, um den Bot zu aktivieren oder bestehende Einträge anzupassen. Ein Klick auf den Turniernamen öffnet das Match direkt auf ipscmatch.de.",
    "v76-fav-title": "Meine Favoriten",
    "v76-fav-subtitle": "Deine drei Schnellzugriffe",
    "v76-fav-edit": "Favoriten bearbeiten",
    "v76-fav-modal-title": "Favoriten wählen",
    "v76-fav-modal-subtitle": "Wähle bis zu drei Bereiche für deine Startseite.",
    "v76-fav-market": "Marktplatz",
    "v76-fav-market-sub": "Startplätze finden",
    "v76-fav-planner": "Mein Planer",
    "v76-fav-planner-sub": "Saison planen",
    "v76-fav-log": "Schießbuch",
    "v76-fav-log-sub": "Einträge & PDF",
    "v76-fav-community": "Community",
    "v76-fav-community-sub": "Austausch",
    "v76-fav-free": "Matches",
    "v76-fav-free-sub": "buchbare Plätze",
    "v76-fav-tools": "Tools",
    "v76-fav-tools-sub": "Training auswerten",
    "v76-fav-reload": "Wiederladen",
    "v76-fav-reload-sub": "Laborierungen",
    "v76-fav-analytics": "Statistiken",
    "v76-fav-analytics-sub": "vergangene Matches",
    "v76-fav-hub": "IPSC Hub",
    "v76-fav-hub-sub": "Links & Infos",
    "v76-fav-timer": "SG-Timer Live",
    "v76-fav-timer-sub": "Live & Drills",
    "v76-timer-tab-live": "Konsole",
    "v76-timer-tab-scores": "Bestenlisten",
    "v76-timer-connect-title": "Timer verbinden",
    "v76-timer-connect-desc": "Verbinde deinen SG Timer, um Live-Signale und Drillzeiten zu steuern.",
    "v76-timer-pair": "Gerät koppeln",
    "v76-timer-remote-title": "RO Fernsteuerung",
    "v76-timer-start-signal": "Startsignal senden",
    "v76-timer-stop": "Stopp"
});
    window.portalTranslations.en = Object.assign(window.portalTranslations.en || {}, {
    "v76-market-desc": "Find slots for fully booked matches or offer your slot when you can no longer attend.",
    "v76-market-status": "",
    "v76-planner-desc": "Keep track of your matches: registrations, waitlist entries and confirmed squads are clearly organized in one place.",
    "v76-planner-status": "Tip: Save your name in your profile exactly as it appears on start lists. This helps the app match publicly available IPSCmatch.de data more reliably. Matches from other platforms can still be added manually.",
    "v76-planner-manual-title": "Add match manually",
    "v76-planner-manual-desc": "When a match is not detected automatically",
    "v76-planner-legend-approved": "confirmed in squad",
    "v76-planner-legend-waitlist-label": "Waitlist",
    "v76-planner-legend-waitlist": "not squadded yet",
    "v76-community-desc": "Ask questions, share training tips and stay connected with other IPSC shooters.",
    "v76-community-status": "",
    "v76-free-desc": "See at a glance which matches still have open slots without opening every match listing individually.",
    "v76-free-status": "The overview updates automatically and only shows matches where MatchSign still reports open slots.",
    "v76-free-list-title": "Available matches",
    "v76-free-source": "Source: MatchSign · occupancy below 100%",
    "v76-log-desc": "Document training, request confirmations, export PDF and keep integrity traceable with hash/QR checks.",
    "v76-log-status": "Tamper protection active: New entries are secured with a hash fingerprint and linked to the previous entry when signed. After confirmation, the entry is locked.",
    "v76-tools-desc": "Score stages, compare results with friends, save frequently used shooter names and export your Hit Factor Battles as PDF.",
    "v76-tools-status": "Saved names, multiple stages and PDF export help you quickly score training groups and small battles.",
    "v76-tools-hf-desc": "Enter shooters, times, hits and stages. The app automatically calculates hit factor, ranking and overall results.",
    "v76-tools-dry-desc": "Generate dry-fire drills and train with par time, random delay and a clear timer display.",
    "v76-tools-dry-start": "Start timer (random delay)",
    "v76-analytics-desc": "Analyze past matches, compare results and keep track of your development.",
    "v76-analytics-status": "Results and hit factor are loaded automatically. For A, C, D hits and misses, you can forward your PractiScore emails after the match to info@ipscboerse.com.",
    "v76-reload-desc": "Save your loads, check power factor and keep proven recipes organized for training and matches.",
    "v76-reload-status": "Calculate power factor using FPS or meters per second. Save your loads as reusable recipes afterwards.",
    "v76-reload-unit-label": "Unit",
    "v76-reload-recipes-desc": "Save proven loads with bullet, powder, velocity, OAL and notes as a personal recipe.",
    "v76-reload-new-entry": "New load",
    "v76-reload-safety": "Note: Always verify loads responsibly using official load data and your own measurements.",
    "v76-hub-desc": "All important IPSC platforms, links and information in one place — from match registration and results to federation resources.",
    "v76-hub-status": "",
    "v76-elo-kicker": "ELO Comparison",
    "v76-elo-title": "ELO Comparison",
    "v76-elo-desc": "Compare your ELO strength with the field of upcoming matches and prepare more realistically before the first shot.",
    "v76-elo-status": "When your correct name is saved in your profile, the app can automatically detect matching upcoming matches. Confirm a match with one tap or paste an IPSCMatch link with division manually.",
    "v76-elo-upcoming-title": "🎯 Automatically detected upcoming matches",
    "v76-elo-welcome-title": "ELO Comparison",
    "v76-elo-welcome-desc": "Select an automatically detected match or paste an IPSCMatch link with division to compare the field with your ELO strength.",
    "v76-bot-kicker": "Club Area",
    "v76-bot-title": "Slot Bot",
    "v76-bot-desc": "Select upcoming matches and let the bot register you automatically as soon as registration opens.",
    "v76-bot-status": "Members only: The bot watches selected matches and tries to register automatically as soon as registration opens.",
    "v76-bot-info": "Here you can see upcoming matches where registration can be prepared. Select a match to activate the bot or adjust existing entries. Tap the match name to open it directly on ipscmatch.de.",
    "v76-fav-title": "My favorites",
    "v76-fav-subtitle": "Your three shortcuts",
    "v76-fav-edit": "Edit favorites",
    "v76-fav-modal-title": "Choose favorites",
    "v76-fav-modal-subtitle": "Choose up to three sections for your home screen.",
    "v76-fav-market": "Marketplace",
    "v76-fav-market-sub": "Find slots",
    "v76-fav-planner": "Planner",
    "v76-fav-planner-sub": "Plan season",
    "v76-fav-log": "Shooting Log",
    "v76-fav-log-sub": "Entries & PDF",
    "v76-fav-community": "Community",
    "v76-fav-community-sub": "Exchange",
    "v76-fav-free": "Open Matches",
    "v76-fav-free-sub": "available slots",
    "v76-fav-tools": "Tools",
    "v76-fav-tools-sub": "score training",
    "v76-fav-reload": "Reloading",
    "v76-fav-reload-sub": "loads",
    "v76-fav-analytics": "Statistics",
    "v76-fav-analytics-sub": "past matches",
    "v76-fav-hub": "IPSC Hub",
    "v76-fav-hub-sub": "links & info",
    "v76-fav-timer": "SG Timer Live",
    "v76-fav-timer-sub": "live & drills",
    "v76-timer-tab-live": "Console",
    "v76-timer-tab-scores": "Leaderboards",
    "v76-timer-connect-title": "Connect timer",
    "v76-timer-connect-desc": "Connect your SG Timer to control live signals and drill times.",
    "v76-timer-pair": "Pair device",
    "v76-timer-remote-title": "RO remote control",
    "v76-timer-start-signal": "Send start signal",
    "v76-timer-stop": "Stop"
});
})();


// V78S: late release translation keys are supplied by release-i18n-v78s.js.

// V79BO: Analytics upload/import/training translations
(function(){
  window.portalTranslations = window.portalTranslations || {};
  window.portalTranslations.de = Object.assign(window.portalTranslations.de || {}, {
  "analytics-kicker": "STATISTIKEN",
  "analytics-hero-title": "Statistiken",
  "analytics-import-title": "Matchdaten importieren",
  "analytics-import-desc": "Lade eine oder mehrere Dateien gleichzeitig: Ergebnisliste, Stage-Results und Verify-PDF. Alternativ kannst du den Text einer PractiScore-/Verify-Mail einfügen. Die Analyse verbindet passende Daten automatisch.",
  "analytics-import-text-ph": "Oder E-Mail-/PDF-Text hier einfügen …",
  "analytics-import-check": "Import prüfen",
  "analytics-import-save": "In meine Analyse speichern",
  "analytics-delete-match": "Match löschen",
  "analytics-delete-confirm": "Dieses Match wirklich löschen? Es werden alle Analyse-Zeilen zu diesem Match aus deinem Profil entfernt.",
  "analytics-delete-running": "Lösche…",
  "analytics-delete-done": "Match gelöscht.",
  "analytics-delete-failed": "Löschen fehlgeschlagen:",
  "analytics-buddy": "Buddy Radar",
  "analytics-empty-title": "Noch keine Match-Daten gefunden",
  "analytics-empty-desc": "Noch keine gespeicherten Matchdaten vorhanden. Lade oben eine Ergebnisliste, Stage-Results oder Verify-PDF hoch.",
  "analytics-empty-import": "<strong>Match-Import:</strong> Upload ist jetzt der Hauptweg. Ergebnislisten und Stage-Results werden direkt im Browser erkannt.",
  "analytics-empty-email": "<strong>Treffer-Analyse:</strong> Verify-PDF oder PractiScore-Mail ergänzt A/C/D/M/PE. Ohne Treffer-Details bleiben nur die offiziellen Ergebnisdaten sichtbar.",
  "analytics-login-btn": "Jetzt einloggen",
  "analytics-tab-analysis": "Analyse",
  "analytics-tab-training": "Trainingsplan",
  "analytics-kpi-division": "Division",
  "analytics-kpi-stage-percent": "Ø Stage %",
  "analytics-kpi-consistency": "Konstanz",
  "analytics-consistency-title": "Was bedeutet Konstanz?",
  "analytics-consistency-desc": "Konstanz zeigt die Spannweite zwischen deiner besten und schlechtesten Stage-Leistung. Je kleiner die Spannweite zwischen bester und schwächster Stage, desto konstanter war dein Match.",
  "analytics-hit-edit": "Stage-Treffer bearbeiten",
  "analytics-training-title": "Automatischer Trainingsplan",
  "analytics-training-desc": "Der Plan wird aus deinen Stage-Prozenten, Trefferdaten, Misses/Procedures und deiner Konstanz erstellt. Er ist bewusst als 4-Wochen-Plan aufgebaut.",
  "analytics-training-empty": "Wähle ein Match aus oder importiere Daten, dann erstelle ich den Plan automatisch.",
  "analytics-source-title": "Datenquelle",
  "analytics-stage-results": "Stage-Ergebnisse",
  "analytics-overall-result": "Overall-Ergebnis",
  "analytics-hit-details": "Trefferdetails A/C/D/M/PE",
  "analytics-source-upload-verify": "Verify-PDF hochladen, um Treffer je Stage automatisch zu übernehmen.",
  "analytics-present": "vorhanden",
  "analytics-missing": "fehlen",
  "analytics-not-separate": "nicht separat",
  "analytics-hit-status-present": "Trefferdetails vorhanden. Einzelne Stages kannst du unten auf der jeweiligen Stage bearbeiten.",
  "analytics-hit-status-missing": "Noch keine A/C/D/M/PE-Daten vorhanden. Lade am besten die Verify-PDF hoch oder bearbeite unten eine einzelne Stage.",
  "analytics-hit-missing-badge": "Trefferdetails fehlen",
  "analytics-import-reading": "Datei wird gelesen …",
  "analytics-import-read-file": "Lese",
  "analytics-import-no-input": "Bitte eine Datei auswählen oder Text einfügen.",
  "analytics-import-no-match": "Keine passenden Daten für deinen Profilnamen gefunden. Prüfe Profilname, Division oder Dateityp.",
  "analytics-preview-title": "Vorschau",
  "analytics-preview-match": "Match",
  "analytics-preview-found": "Gefunden",
  "analytics-preview-rows": "Zeilen",
  "analytics-preview-stages": "Stages",
  "analytics-preview-overall": "Overall",
  "analytics-preview-hitrows": "Treffer-Zeilen",
  "analytics-preview-ready": "Bereit zum Speichern.",
  "analytics-import-done": "Prüfung fertig.",
  "analytics-import-failed": "Import konnte nicht vorbereitet werden.",
  "analytics-saved": "Zeilen gespeichert. Analyse aktualisiert.",
  "analytics-save-running": "Speichere in Supabase …",
  "analytics-save-failed": "Speichern fehlgeschlagen:",
  "analytics-not-logged-in": "Nicht angemeldet.",
  "analytics-type-verify": "Verify / Treffer",
  "analytics-type-mail": "E-Mail / Treffer",
  "analytics-type-stagepdf": "Stage-Results PDF",
  "analytics-type-resultpdf": "Ergebnisliste PDF",
  "analytics-type-import": "Import"
});
  window.portalTranslations.en = Object.assign(window.portalTranslations.en || {}, {
  "analytics-kicker": "STATISTICS",
  "analytics-hero-title": "Statistics",
  "analytics-import-title": "Import match data",
  "analytics-import-desc": "Upload one or more files at once: overall results, stage results and verification PDF. Alternatively paste PractiScore/verification email text. The analysis combines matching data automatically.",
  "analytics-import-text-ph": "Paste email/PDF text here …",
  "analytics-import-check": "Check import",
  "analytics-import-save": "Save to my analysis",
  "analytics-delete-match": "Delete match",
  "analytics-delete-confirm": "Really delete this match? All analysis rows for this match will be removed from your profile.",
  "analytics-delete-running": "Deleting…",
  "analytics-delete-done": "Match deleted.",
  "analytics-delete-failed": "Delete failed:",
  "analytics-buddy": "Buddy Radar",
  "analytics-empty-title": "No match data found yet",
  "analytics-empty-desc": "No saved match data yet. Upload an overall result, stage-results PDF or verification PDF above.",
  "analytics-empty-import": "<strong>Match import:</strong> Upload is now the main workflow. Overall results and stage-results PDFs are detected directly in the browser.",
  "analytics-empty-email": "<strong>Hit analysis:</strong> Verification PDFs or PractiScore emails add A/C/D/M/PE. Without hit details, only official result data is shown.",
  "analytics-login-btn": "Log in now",
  "analytics-tab-analysis": "Analysis",
  "analytics-tab-training": "Training plan",
  "analytics-kpi-division": "Division",
  "analytics-kpi-stage-percent": "Ø Stage %",
  "analytics-kpi-consistency": "Consistency",
  "analytics-consistency-title": "What does consistency mean?",
  "analytics-consistency-desc": "Consistency shows the spread between your best and weakest stage performance. The smaller the spread, the more consistent your match was.",
  "analytics-hit-edit": "Edit stage hits",
  "analytics-training-title": "Automatic training plan",
  "analytics-training-desc": "The plan is created from your stage percentages, hit data, misses/procedures and consistency. It is intentionally structured as a 4-week plan.",
  "analytics-training-empty": "Select a match or import data, then I will create the plan automatically.",
  "analytics-source-title": "Data source",
  "analytics-stage-results": "Stage results",
  "analytics-overall-result": "Overall result",
  "analytics-hit-details": "Hit details A/C/D/M/PE",
  "analytics-source-upload-verify": "Upload the verification PDF to import hits per stage automatically.",
  "analytics-present": "available",
  "analytics-missing": "missing",
  "analytics-not-separate": "not separate",
  "analytics-hit-status-present": "Hit details available. You can edit individual stages on the stage card below.",
  "analytics-hit-status-missing": "No A/C/D/M/PE data yet. Upload the verification PDF or edit an individual stage below.",
  "analytics-hit-missing-badge": "Hit details missing",
  "analytics-import-reading": "Reading file …",
  "analytics-import-read-file": "Reading",
  "analytics-import-no-input": "Please choose a file or paste text.",
  "analytics-import-no-match": "No matching data found for your profile name. Check profile name, division or file type.",
  "analytics-preview-title": "Preview",
  "analytics-preview-match": "Match",
  "analytics-preview-found": "Found",
  "analytics-preview-rows": "rows",
  "analytics-preview-stages": "stages",
  "analytics-preview-overall": "overall",
  "analytics-preview-hitrows": "hit rows",
  "analytics-preview-ready": "Ready to save.",
  "analytics-import-done": "Check complete.",
  "analytics-import-failed": "Import could not be prepared.",
  "analytics-saved": "Rows saved. Analysis updated.",
  "analytics-save-running": "Saving to Supabase …",
  "analytics-save-failed": "Save failed:",
  "analytics-not-logged-in": "Not logged in.",
  "analytics-type-verify": "Verification / hits",
  "analytics-type-mail": "Email / hits",
  "analytics-type-stagepdf": "Stage-results PDF",
  "analytics-type-resultpdf": "Overall-results PDF",
  "analytics-type-import": "Import"
});
  window.translations = window.portalTranslations;
  try { if (typeof window.translatePortalPage === "function") window.translatePortalPage(); } catch (_) {}
})();
