name: run-email-bot

on:
  schedule:
    - cron: '0 4 * * *' # Läuft automatisch jeden Tag (Beispiel)
  workflow_dispatch: # Erlaubt den grauen "Run workflow" Button auf dem Handy

jobs:
  email-job:
    runs-on: ubuntu-latest
    steps:
      - name: Code auschecken
        uses: actions/checkout@v4

      - name: Python installieren
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: E-Mail Bot ausführen (PractiScore)
        run: python ipscboerse.com/read_practiscore_mails.py
